#!/usr/bin/env python3
"""Execute RET-001 Extension↔companion replay observations.

The Extension side of each scenario is generated by
``produce-ret-001-extension-state.mjs`` using the production DurableIngestOutbox
and IndexedDB adapter. This consumer feeds those exact records into the existing
companion HistoryRepository. Direct SQL mutation is confined to isolated test
SQLite files and does not create a production deletion API.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
from tempfile import TemporaryDirectory
from uuid import UUID

from app.protocol.payloads import (
    IngestDeltaPayload,
    IngestSnapshotBeginPayload,
    IngestSnapshotChunkPayload,
    IngestSnapshotCommitPayload,
)

ROOT = Path(__file__).resolve().parents[2]
LIBRARY_PATH = Path(__file__).with_name("run-ret-001-companion-observations.py")
_SPEC = importlib.util.spec_from_file_location("ret001_companion_observation_library", LIBRARY_PATH)
if _SPEC is None or _SPEC.loader is None:
    raise RuntimeError(f"Unable to load RET-001 observation library {LIBRARY_PATH}")
lib = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(lib)

CONNECTION_ID = UUID("70000000-0000-4000-8000-000000000001")
INSTALLATION_ID = UUID("71000000-0000-4000-8000-000000000001")
FENCING_TOKEN = "ret001-observation-fence"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--product-revision", required=True)
    parser.add_argument("--extension-state", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser.parse_args()


def identity(account_id: str, stream_id: str) -> dict:
    return {
        "connection_id": CONNECTION_ID,
        "fencing_token": FENCING_TOKEN,
        "creator_account_id": account_id,
        "agent_installation_id": INSTALLATION_ID,
        "agent_stream_id": UUID(stream_id),
    }


def stream_key(account_id: str, stream_id: str):
    return lib.StreamKey(account_id, INSTALLATION_ID, UUID(stream_id))


def ingest_snapshot(history, account_id: str, stream_id: str, snapshot: dict) -> dict:
    key = stream_key(account_id, stream_id)
    bound = identity(account_id, stream_id)
    begin = IngestSnapshotBeginPayload(**bound, **snapshot["begin"])
    begin_result = history.begin_snapshot(key, begin)
    chunk_results = []
    for document in snapshot["chunks"]:
        chunk = IngestSnapshotChunkPayload(**bound, **document)
        chunk_results.append(history.add_snapshot_chunk(key, chunk))
    commit = IngestSnapshotCommitPayload(**bound, **snapshot["commit"])
    commit_result = history.commit_snapshot(key, commit)
    return {
        "begin": begin_result.status,
        "chunks": [result.status for result in chunk_results],
        "commit": commit_result.status,
        "committed_source_seq": commit_result.committed_source_seq,
        "snapshot_committed": commit_result.snapshot_committed,
    }


def ingest_delta(history, account_id: str, stream_id: str, item: dict):
    payload = IngestDeltaPayload(
        **identity(account_id, stream_id),
        event_id=UUID(item["event_id"]),
        source_seq=item["source_seq"],
        acquisition_origin=item.get("acquisition_origin", "passive"),
        change=item["change"],
    )
    return history.commit_delta(stream_key(account_id, stream_id), payload)


def seed_empty_snapshot(history, account_id: str, stream_id: str, snapshot_id: str) -> None:
    key = stream_key(account_id, stream_id)
    bound = identity(account_id, stream_id)
    begin = IngestSnapshotBeginPayload(
        **bound,
        snapshot_id=UUID(snapshot_id),
        frame_kind="begin",
        through_seq=0,
        chunk_count=0,
        record_counts={"chats": 0, "messages": 0, "coverage_evidence": 0},
        max_frame_bytes=524288,
    )
    result = history.begin_snapshot(key, begin)
    if result.status != "accepted":
        raise RuntimeError(f"empty snapshot begin failed: {result.status}")
    commit = IngestSnapshotCommitPayload(
        **bound,
        snapshot_id=UUID(snapshot_id),
        frame_kind="commit",
        chunk_count=0,
    )
    committed = history.commit_snapshot(key, commit)
    if committed.status != "accepted":
        raise RuntimeError(f"empty snapshot commit failed: {committed.status}")


def delete_companion_delivery_and_message(database, account_id: str, message_id: str) -> None:
    with database.transaction() as connection:
        connection.execute(
            "DELETE FROM raw_ingest_events WHERE creator_account_id=?",
            (account_id,),
        )
        connection.execute(
            "DELETE FROM account_messages WHERE creator_account_id=? AND message_id=?",
            (account_id, message_id),
        )


def delete_canonical_message(database, account_id: str, message_id: str) -> None:
    with database.transaction() as connection:
        connection.execute(
            "DELETE FROM account_messages WHERE creator_account_id=? AND message_id=?",
            (account_id, message_id),
        )


def raw_event_count(database, account_id: str) -> int:
    with database.read() as connection:
        return int(
            connection.execute(
                "SELECT COUNT(*) FROM raw_ingest_events WHERE creator_account_id=?",
                (account_id,),
            ).fetchone()[0]
        )


def make_result(scenario_id: str, revision: str, status: str, observations: list[dict], notes: list[str]):
    return lib.result_document(
        scenario_id,
        revision,
        status,
        observations,
        notes=notes,
    )


def run_res_001(root: Path, revision: str, document: dict) -> dict:
    state = document["pending_delivery"]
    account_id = document["creator_account_id"]
    stream_id = state["restarted_identity"]["agent_stream_id"]
    repositories = lib.create_canonical_repositories(
        "sqlite",
        canonical_path=root / "res-001-canonical.sqlite3",
        projection_path=root / "res-001-projections.sqlite3",
    )
    seed_empty_snapshot(
        repositories.history,
        account_id,
        stream_id,
        "72000000-0000-4000-8000-000000000001",
    )
    first_results = [
        ingest_delta(repositories.history, account_id, stream_id, item)
        for item in state["outbox_after_restart"]
    ]
    message_id = state["message_source"]["message_id"]
    before = lib.canonical_message(repositories.database, account_id, message_id)
    if before is None:
        raise RuntimeError("RES-001 precondition failed: first outbox delivery did not create message")
    raw_before = raw_event_count(repositories.database, account_id)

    delete_companion_delivery_and_message(repositories.database, account_id, message_id)
    if lib.canonical_message(repositories.database, account_id, message_id) is not None:
        raise RuntimeError("RES-001 test-only canonical deletion failed")
    replay_results = [
        ingest_delta(repositories.history, account_id, stream_id, item)
        for item in state["outbox_after_restart"]
    ]
    after = lib.canonical_message(repositories.database, account_id, message_id)
    raw_after = raw_event_count(repositories.database, account_id)
    reentered = after is not None

    return make_result(
        "RES-001-EXT-OUTBOX-RETRY",
        revision,
        "OBSERVED_REENTRY" if reentered else "NO_REENTRY_OBSERVED",
        [
            {
                "relationship_requirement_id": "RES-001-R1",
                "outcome": "OBSERVED" if raw_after > 0 else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-001-EXTENSION-OUTBOX-RETRY"],
                "facts": {
                    "extension_outbox_survived_worker_restart": state["outbox_before_restart"] == state["outbox_after_restart"],
                    "initial_delivery_statuses": [item.status for item in first_results],
                    "raw_ingest_event_count_before_test_delete": raw_before,
                    "retry_statuses_after_test_delete": [item.status for item in replay_results],
                    "raw_ingest_event_count_after_retry": raw_after,
                },
            },
            {
                "relationship_requirement_id": "RES-001-R2",
                "outcome": "OBSERVED" if reentered else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-001-CANONICAL-REENTRY"],
                "facts": {
                    "canonical_message_before_test_delete": before,
                    "canonical_message_after_retry": after,
                    "canonical_message_reentered": reentered,
                },
            },
        ],
        [
            "The queued Extension records are emitted by the production DurableIngestOutbox and survive a simulated worker restart before companion ingestion.",
            "The companion raw-ingest rows and canonical message are deleted only in the isolated characterization database; the ingest checkpoint intentionally survives.",
            "A NO_REENTRY_OBSERVED result describes this exact retry path and does not establish a general deletion guarantee.",
        ],
    )


def run_res_002(root: Path, revision: str, document: dict) -> dict:
    state = document["snapshot_replay"]
    account_id = document["creator_account_id"]
    stream_id = state["identity"]["agent_stream_id"]
    repositories = lib.create_canonical_repositories(
        "sqlite",
        canonical_path=root / "res-002-canonical.sqlite3",
        projection_path=root / "res-002-projections.sqlite3",
    )
    first = ingest_snapshot(repositories.history, account_id, stream_id, state["first_snapshot"])
    message_id = state["message_source"]["message_id"]
    before = lib.canonical_message(repositories.database, account_id, message_id)
    if before is None:
        raise RuntimeError("RES-002 precondition failed: first snapshot did not create message")
    delete_canonical_message(repositories.database, account_id, message_id)
    second = ingest_snapshot(
        repositories.history,
        account_id,
        stream_id,
        state["second_snapshot_from_same_extension_state"],
    )
    after = lib.canonical_message(repositories.database, account_id, message_id)
    reentered = after is not None
    return make_result(
        "RES-002-HISTORY-SNAPSHOT-REPLAY",
        revision,
        "OBSERVED_REENTRY" if reentered else "NO_REENTRY_OBSERVED",
        [
            {
                "relationship_requirement_id": "RES-002-R1",
                "outcome": "OBSERVED" if reentered else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-002-SECOND-EXTENSION-SNAPSHOT"],
                "facts": {
                    "first_snapshot_ingest": first,
                    "extension_outbox_empty_after_first_snapshot_ack": state["outbox_after_first_snapshot_ack"] == [],
                    "second_snapshot_ingest": second,
                    "canonical_message_before_test_delete": before,
                    "canonical_message_after_second_snapshot": after,
                    "canonical_message_reentered": reentered,
                },
            }
        ],
        [
            "The second snapshot is freshly generated from the same surviving Extension entity state after the first snapshot was acknowledged and its outbox was emptied.",
            "The canonical row deletion is test-only and occurs between the two otherwise ordinary snapshot ingestion sequences.",
        ],
    )


def run_res_006(root: Path, revision: str, document: dict) -> dict:
    state = document["acknowledged_message_state"]
    account_id = document["creator_account_id"]
    stream_id = state["identity"]["agent_stream_id"]
    repositories = lib.create_canonical_repositories(
        "sqlite",
        canonical_path=root / "res-006-canonical.sqlite3",
        projection_path=root / "res-006-projections.sqlite3",
    )
    snapshot = state["snapshot_after_acknowledgement"]
    first = ingest_snapshot(repositories.history, account_id, stream_id, snapshot)
    message_id = state["message_source"]["message_id"]
    before = lib.canonical_message(repositories.database, account_id, message_id)
    if before is None:
        raise RuntimeError("RES-006 precondition failed: acknowledged Extension snapshot did not create message")
    delete_canonical_message(repositories.database, account_id, message_id)

    # Reusing the same already-committed snapshot id exercises the actual stale
    # replay behavior. The repository is expected either to report duplicate or
    # to reapply content; the observation records which occurs.
    replay = ingest_snapshot(repositories.history, account_id, stream_id, snapshot)
    after = lib.canonical_message(repositories.database, account_id, message_id)
    reentered = after is not None
    return make_result(
        "RES-006-STALE-EXTENSION-AFTER-COMPANION-DELETE",
        revision,
        "OBSERVED_REENTRY" if reentered else "NO_REENTRY_OBSERVED",
        [
            {
                "relationship_requirement_id": "RES-006-R1",
                "outcome": "OBSERVED" if reentered else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-006-ACKNOWLEDGED-EXTENSION-SNAPSHOT-REPLAY"],
                "facts": {
                    "extension_outbox_empty_before_snapshot": state["outbox_after_acknowledgement"] == [],
                    "initial_snapshot_ingest": first,
                    "stale_same_snapshot_replay": replay,
                    "canonical_message_before_test_delete": before,
                    "canonical_message_after_stale_replay": after,
                    "canonical_message_reentered": reentered,
                },
            }
        ],
        [
            "This scenario distinguishes durable Extension entity state from its already-acknowledged outbox: the outbox is empty, but the message is still snapshot-capable.",
            "The same committed snapshot identity is replayed after test-only companion deletion to characterize deduplication versus reapplication behavior.",
        ],
    )


def run_res_008(root: Path, revision: str, document: dict) -> dict:
    state = document["pending_delivery"]
    account_id = document["creator_account_id"]
    stream_id = state["restarted_identity"]["agent_stream_id"]
    repositories = lib.create_canonical_repositories(
        "sqlite",
        canonical_path=root / "res-008-canonical.sqlite3",
        projection_path=root / "res-008-projections.sqlite3",
    )
    seed_empty_snapshot(
        repositories.history,
        account_id,
        stream_id,
        "78000000-0000-4000-8000-000000000001",
    )
    results = [
        ingest_delta(repositories.history, account_id, stream_id, item)
        for item in state["outbox_after_restart"]
    ]
    message_id = state["message_source"]["message_id"]
    after = lib.canonical_message(repositories.database, account_id, message_id)
    raw_count = raw_event_count(repositories.database, account_id)
    accepted = all(item.status in {"accepted", "duplicate"} for item in results)
    canonical_present = after is not None
    return make_result(
        "RES-008-RECONNECT-AFTER-DISCONNECT",
        revision,
        "OBSERVED_REENTRY" if canonical_present else "NO_REENTRY_OBSERVED",
        [
            {
                "relationship_requirement_id": "RES-008-R1",
                "outcome": "OBSERVED" if raw_count > 0 else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-008-RESTARTED-OUTBOX-DELIVERY"],
                "facts": {
                    "extension_outbox_survived_worker_restart": state["outbox_before_restart"] == state["outbox_after_restart"],
                    "delivery_statuses": [item.status for item in results],
                    "delivery_accepted_or_duplicate": accepted,
                    "raw_ingest_event_count": raw_count,
                },
            },
            {
                "relationship_requirement_id": "RES-008-R2",
                "outcome": "OBSERVED" if canonical_present else "NOT_OBSERVED",
                "evidence_ids": ["EXEC-RES-008-RAW-TO-CANONICAL"],
                "facts": {
                    "canonical_message_after_restarted_delivery": after,
                    "canonical_message_present": canonical_present,
                },
            },
        ],
        [
            "This is a bounded reconnect/restart characterization: queued durable Extension state survives construction of a new outbox instance and is then accepted by an initialized companion stream.",
            "It does not claim to exercise network transport timing, credential refresh, or every reconnect branch in AgentWebSocketClient.",
        ],
    )


def main() -> int:
    args = parse_args()
    if len(args.product_revision) != 40 or any(
        character not in "0123456789abcdef" for character in args.product_revision
    ):
        raise SystemExit("--product-revision must be a lowercase 40-hex commit SHA")
    document = json.loads(args.extension_state.read_text(encoding="utf-8"))
    if document.get("schema") != "ofca-ret-001-extension-replay-fixtures/v1":
        raise SystemExit("Extension replay fixture schema differs")
    if document.get("product_revision") != args.product_revision:
        raise SystemExit("Extension replay fixture Product revision differs")
    args.output_dir.mkdir(parents=True, exist_ok=True)

    with TemporaryDirectory(prefix="ret-001-cross-boundary-") as temporary:
        root = Path(temporary)
        results = [
            run_res_001(root, args.product_revision, document),
            run_res_002(root, args.product_revision, document),
            run_res_006(root, args.product_revision, document),
            run_res_008(root, args.product_revision, document),
        ]

    for result in results:
        destination = args.output_dir / f"{result['scenario_id'].lower()}.json"
        destination.write_text(
            json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    print(
        json.dumps(
            {
                "schema": "ofca-ret-001-cross-boundary-observation-run/v1",
                "product_revision": args.product_revision,
                "executed_scenario_ids": sorted(result["scenario_id"] for result in results),
                "result_statuses": {
                    result["scenario_id"]: result["result_status"] for result in results
                },
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
