 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = "connection_ack";
export type Version = string;
export type Clienttype = string | null;
export type Userid = string | null;
export type Statusmessage = string | null;
export type Type1 = "system_status";
export type Status = "PROCESSING_SNAPSHOT" | "REALTIME" | "ERROR";
export type Detail = string | null;
export type Type2 = "system_error";
export type Errormessage = string;
export type Code = string | null;
export type Detail1 = string | null;
export type Type3 = "full_sync_response";
export type Conversationid = string;
export type Startdate = string;
export type Enddate = string | null;
export type Messagecount = number;
export type Averageresponsetime = number | null;
export type Turns = number | null;
export type Silencepercentage = number | null;
export type Messages = Message[] | null;
export type Id = number | string;
export type ChatId = number | string | null;
export type Text = string | null;
export type Createdat = string | null;
export type CreatedAt = string | null;
export type Changedat = string | null;
export type Id1 = number | string | null;
export type View = string | null;
export type Name = string | null;
export type Username = string | null;
export type Displayname = string | null;
export type Avatar = string | null;
export type C50 = string | null;
export type C144 = string | null;
export type Header = string | null;
export type Width = number | null;
export type Height = number | null;
export type W480 = string | null;
export type W760 = string | null;
export type Lastseen = string | null;
export type Notice = string | null;
export type Canaddsubscriber = boolean | null;
export type Cancommentstory = boolean | null;
export type Canearn = boolean | null;
export type Canlookstory = boolean | null;
export type Canpayinternal = boolean | null;
export type Canrestrict = boolean | null;
export type Currentsubscribeprice = number | null;
export type Hasnotviewedstory = boolean | null;
export type Hasscheduledstream = boolean | null;
export type Hasstories = boolean | null;
export type Hasstream = boolean | null;
export type Ispaywallrequired = boolean | null;
export type Isrestricted = boolean | null;
export type Isverified = boolean | null;
export type Listsstates =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type Showmediacount = boolean | null;
export type Subscribeprice = number | null;
export type Subscribedby = boolean | null;
export type Subscribedbyautoprolong = boolean | null;
export type Subscribedbyexpire = boolean | null;
export type Subscribedbyexpiredate = string | null;
export type Subscribedisexpirednow = boolean | null;
export type Subscribedon = boolean | null;
export type Subscribedonduration = string | null;
export type Subscribedonexpirednow = boolean | null;
export type Subscriptionbundles =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type Tipsenabled = boolean | null;
export type Tipsmax = number | null;
export type Tipsmin = number | null;
export type Tipsmininternal = number | null;
export type Tipstextenabled = boolean | null;
export type IsCreator = boolean | null;
/**
 * Sentiment score between 0 and 1
 */
export type Sentimentscore = number | null;
/**
 * List of NLP-extracted topics
 */
export type Topics = string[] | null;
export type IsInbound = boolean | null;
export type Ispinned = boolean | null;
export type Istip = boolean | null;
export type Isliked = boolean | null;
export type Isfree = boolean | null;
export type Iscouplepeoplemedia = boolean | null;
export type Ismarkdowndisabled = boolean | null;
export type Ismediaready = boolean | null;
export type Isnew = boolean | null;
export type Isopened = boolean | null;
export type Isreportedbyme = boolean | null;
export type Isfromqueue = boolean | null;
export type Canbepinned = boolean | null;
export type Canpurchase = boolean | null;
export type Canpurchasereason = string | null;
export type Canreport = boolean | null;
export type Canunsendqueue = boolean | null;
export type Mediacount = number | null;
export type Price = number | null;
export type Cancelseconds = number | null;
export type Queueid = number | string | null;
export type Unsendsecondsqueue = number | null;
export type Giphyid = string | null;
export type Lockedtext = boolean | null;
export type Responsetype = string | null;
export type Media = MediaItem[] | null;
export type Canview = boolean | null;
export type Convertedtovideo = boolean | null;
export type Createdat1 = string | null;
export type Duration = number | null;
export type Files = {
  [k: string]: MediaFile;
} | null;
export type Height1 = number | null;
export type Size = number | null;
export type Sources = string[] | null;
export type Url = string | null;
export type Width1 = number | null;
export type Height2 = number | null;
export type Size1 = number | null;
export type Url1 = string | null;
export type Width2 = number | null;
export type Squarepreview = {
  [k: string]: unknown;
} | null;
export type Thumb = {
  [k: string]: unknown;
} | null;
export type Hascustompreview = boolean | null;
export type Haserror = boolean | null;
export type Id2 = number | string | null;
export type Isready = boolean | null;
export type Type4 = string | null;
export type Videosources = {
  [k: string]: string | null;
} | null;
export type Previews =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type Releaseforms =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type Topics1 = Topic[] | null;
export type Topicid = string;
export type Description = string;
export type Embedding = number[];
export type Category = string | null;
export type Actions = EngagementAction[] | null;
export type Actionid = string;
export type Name1 = string;
export type Embedding1 = number[];
export type Type5 = string | null;
export type Sentiment = number | null;
export type Outcomes = InteractionOutcome[] | null;
export type Outcomeid = string;
export type Name2 = string;
export type Score = number | null;
export type Date = string | null;
export type Priorityscore = number | null;
export type Conversations = ExtendedConversationNode[];
export type Topic1 = string;
export type Volume = number;
export type PercentageOfTotal = number;
export type Trend = number | null;
export type Topics2 = TopicMetricsResponse[];
export type Date1 = string;
export type SentimentScore = number;
export type Trend1 = SentimentTrendPoint[];
export type AverageHandlingTimeMinutes = number;
export type SilencePercentage = number;
export type Turns1 = number;
export type Priorityscores = {
  [k: string]: number;
} | null;
export type Unreadcounts = {
  [k: string]: number;
} | null;
export type Type6 = "append_message";
export type Type7 = "analytics_update";
export type Type8 = "command_to_execute";
/**
 * The target chat thread ID
 */
export type ChatId1 = number | string;
/**
 * The message text to send
 */
export type Text1 = string;
/**
 * Optional media attachment URL
 */
export type MediaUrl = string | null;
export type Type9 = "enrichment_result";
export type Conversationid1 = string;
export type Topics3 = Topic[];
export type Actions1 = EngagementAction[];
export type Sentiment1 = number;
export type Outcomes1 = InteractionOutcome[];
export type Type10 = "online_users_update";
/**
 * List of currently online user IDs
 */
export type UserIds = number[];
/**
 * ISO8601 timestamp of the presence update
 */
export type Timestamp = string;

/**
 * Sent immediately upon WS connection acceptance.
 */
export interface ConnectionAckMsg {
  type?: Type;
  payload: ConnectionInfo;
  [k: string]: unknown;
}
/**
 * Sent immediately on WSS connect — confirms connection and provides system version.
 */
export interface ConnectionInfo {
  version: Version;
  clientType?: Clienttype;
  userId?: Userid;
  statusMessage?: Statusmessage;
  [k: string]: unknown;
}
/**
 * Broadcasts current backend status.
 */
export interface SystemStatusMsg {
  type?: Type1;
  payload: SystemStatus;
  [k: string]: unknown;
}
/**
 * Represents the current operational status of the Brain.
 */
export interface SystemStatus {
  status: Status;
  detail?: Detail;
  [k: string]: unknown;
}
/**
 * Reports server-side processing/parsing error.
 */
export interface SystemErrorMsg {
  type?: Type2;
  payload: WssError;
  [k: string]: unknown;
}
/**
 * Represents an error sent over WS to the Bridge.
 */
export interface WssError {
  errorMessage: Errormessage;
  code?: Code;
  detail?: Detail1;
  [k: string]: unknown;
}
/**
 * Snapshot: complete graph + analytics.
 */
export interface FullSyncResponseMsg {
  type?: Type3;
  payload: FullSyncResponse;
  [k: string]: unknown;
}
/**
 * Complete snapshot of all conversations, analytics, and graph data.
 * Sent once after processing a cache_update (snapshot ingestion).
 */
export interface FullSyncResponse {
  conversations: Conversations;
  analytics: AnalyticsUpdate;
  [k: string]: unknown;
}
/**
 * Extended ConversationNode including additional frontend/UI and prioritization fields.
 *
 * Used in WS payloads when the frontend requires richer context,
 * such as displaying the other participant's profile or ranking conversations.
 */
export interface ExtendedConversationNode {
  conversationId: Conversationid;
  startDate: Startdate;
  endDate?: Enddate;
  messageCount: Messagecount;
  averageResponseTime?: Averageresponsetime;
  turns?: Turns;
  silencePercentage?: Silencepercentage;
  messages?: Messages;
  topics?: Topics1;
  actions?: Actions;
  sentiment?: Sentiment;
  outcomes?: Outcomes;
  priorityScore?: Priorityscore;
  withUser?: UserRef | null;
  [k: string]: unknown;
}
/**
 * Represents a single OnlyFans chat message, optionally enriched.
 */
export interface Message {
  id: Id;
  chat_id?: ChatId;
  text?: Text;
  createdAt?: Createdat;
  created_at?: CreatedAt;
  changedAt?: Changedat;
  fromUser?: UserRef | null;
  is_creator?: IsCreator;
  sentimentScore?: Sentimentscore;
  topics?: Topics;
  is_inbound?: IsInbound;
  isPinned?: Ispinned;
  isTip?: Istip;
  isLiked?: Isliked;
  isFree?: Isfree;
  isCouplePeopleMedia?: Iscouplepeoplemedia;
  isMarkdownDisabled?: Ismarkdowndisabled;
  isMediaReady?: Ismediaready;
  isNew?: Isnew;
  isOpened?: Isopened;
  isReportedByMe?: Isreportedbyme;
  isFromQueue?: Isfromqueue;
  canBePinned?: Canbepinned;
  canPurchase?: Canpurchase;
  canPurchaseReason?: Canpurchasereason;
  canReport?: Canreport;
  canUnsendQueue?: Canunsendqueue;
  mediaCount?: Mediacount;
  price?: Price;
  cancelSeconds?: Cancelseconds;
  queueId?: Queueid;
  unsendSecondsQueue?: Unsendsecondsqueue;
  giphyId?: Giphyid;
  lockedText?: Lockedtext;
  responseType?: Responsetype;
  media?: Media;
  previews?: Previews;
  releaseForms?: Releaseforms;
  replyToMessage?: Message | null;
  extra?: Extra1;
  [k: string]: unknown;
}
/**
 * Minimal OnlyFans user reference with optional extended profile fields.
 */
export interface UserRef {
  id?: Id1;
  view?: View;
  name?: Name;
  username?: Username;
  displayName?: Displayname;
  avatar?: Avatar;
  avatarThumbs?: AvatarThumbs | null;
  header?: Header;
  headerSize?: HeaderSize | null;
  headerThumbs?: HeaderThumbs | null;
  lastSeen?: Lastseen;
  notice?: Notice;
  canAddSubscriber?: Canaddsubscriber;
  canCommentStory?: Cancommentstory;
  canEarn?: Canearn;
  canLookStory?: Canlookstory;
  canPayInternal?: Canpayinternal;
  canRestrict?: Canrestrict;
  currentSubscribePrice?: Currentsubscribeprice;
  hasNotViewedStory?: Hasnotviewedstory;
  hasScheduledStream?: Hasscheduledstream;
  hasStories?: Hasstories;
  hasStream?: Hasstream;
  isPaywallRequired?: Ispaywallrequired;
  isRestricted?: Isrestricted;
  isVerified?: Isverified;
  listsStates?: Listsstates;
  showMediaCount?: Showmediacount;
  subscribePrice?: Subscribeprice;
  subscribedBy?: Subscribedby;
  subscribedByAutoprolong?: Subscribedbyautoprolong;
  subscribedByExpire?: Subscribedbyexpire;
  subscribedByExpireDate?: Subscribedbyexpiredate;
  subscribedIsExpiredNow?: Subscribedisexpirednow;
  subscribedOn?: Subscribedon;
  subscribedOnDuration?: Subscribedonduration;
  subscribedOnExpiredNow?: Subscribedonexpirednow;
  subscriptionBundles?: Subscriptionbundles;
  tipsEnabled?: Tipsenabled;
  tipsMax?: Tipsmax;
  tipsMin?: Tipsmin;
  tipsMinInternal?: Tipsmininternal;
  tipsTextEnabled?: Tipstextenabled;
  extra?: Extra;
  [k: string]: unknown;
}
export interface AvatarThumbs {
  c50?: C50;
  c144?: C144;
  [k: string]: unknown;
}
export interface HeaderSize {
  width?: Width;
  height?: Height;
  [k: string]: unknown;
}
export interface HeaderThumbs {
  w480?: W480;
  w760?: W760;
  [k: string]: unknown;
}
export interface Extra {
  [k: string]: unknown;
}
export interface MediaItem {
  canView?: Canview;
  convertedToVideo?: Convertedtovideo;
  createdAt?: Createdat1;
  duration?: Duration;
  files?: Files;
  preview?: MediaPreview | null;
  squarePreview?: Squarepreview;
  thumb?: Thumb;
  hasCustomPreview?: Hascustompreview;
  hasError?: Haserror;
  id?: Id2;
  isReady?: Isready;
  type?: Type4;
  videoSources?: Videosources;
  [k: string]: unknown;
}
export interface MediaFile {
  height?: Height1;
  size?: Size;
  sources?: Sources;
  url?: Url;
  width?: Width1;
  [k: string]: unknown;
}
export interface MediaPreview {
  height?: Height2;
  size?: Size1;
  url?: Url1;
  width?: Width2;
  [k: string]: unknown;
}
export interface Extra1 {
  [k: string]: unknown;
}
/**
 * Represents a topic vertex in the LPG.
 */
export interface Topic {
  topicId: Topicid;
  description: Description;
  embedding: Embedding;
  category?: Category;
  [k: string]: unknown;
}
/**
 * Represents an engagement action vertex in the LPG.
 */
export interface EngagementAction {
  actionId: Actionid;
  name: Name1;
  embedding: Embedding1;
  type?: Type5;
  [k: string]: unknown;
}
/**
 * Represents an interaction outcome vertex in the LPG.
 */
export interface InteractionOutcome {
  outcomeId: Outcomeid;
  name: Name2;
  score?: Score;
  date?: Date;
  [k: string]: unknown;
}
/**
 * Granular update to analytics metrics.
 * Used for both snapshot and delta WS payloads.
 */
export interface AnalyticsUpdate {
  topics: Topics2;
  sentiment_trend: SentimentTrendResponse;
  response_time_metrics: ResponseTimeMetricsResponse;
  priorityScores?: Priorityscores;
  unreadCounts?: Unreadcounts;
  [k: string]: unknown;
}
/**
 * Aggregated metrics for a specific topic.
 */
export interface TopicMetricsResponse {
  topic: Topic1;
  volume: Volume;
  percentage_of_total: PercentageOfTotal;
  trend?: Trend;
  [k: string]: unknown;
}
/**
 * Time series of sentiment scores.
 */
export interface SentimentTrendResponse {
  trend: Trend1;
  [k: string]: unknown;
}
/**
 * Represents a single point in a sentiment trend timeline.
 */
export interface SentimentTrendPoint {
  date: Date1;
  sentiment_score: SentimentScore;
  [k: string]: unknown;
}
/**
 * Metrics related to response times and conversation turns.
 */
export interface ResponseTimeMetricsResponse {
  average_handling_time_minutes: AverageHandlingTimeMinutes;
  silence_percentage: SilencePercentage;
  turns: Turns1;
  [k: string]: unknown;
}
/**
 * Delta: single new/updated conversation node.
 * Uses ExtendedConversationNode (superset of ConversationNode).
 */
export interface AppendMessageMsg {
  type?: Type6;
  payload: ExtendedConversationNode;
  [k: string]: unknown;
}
/**
 * Delta: granular analytics metric update.
 */
export interface AnalyticsUpdateMsg {
  type?: Type7;
  payload: AnalyticsUpdate;
  [k: string]: unknown;
}
/**
 * AI-generated command for Agent execution.
 */
export interface CommandToExecuteMsg {
  type?: Type8;
  payload: SendMessageCommand;
  [k: string]: unknown;
}
/**
 * Represents a command instructing the Agent to send a message to a fan.
 */
export interface SendMessageCommand {
  chat_id: ChatId1;
  text: Text1;
  media_url?: MediaUrl;
  [k: string]: unknown;
}
/**
 * Optional extra: enrichment results streamed separately
 * from append_message/analytics_update.
 */
export interface EnrichmentResultMsg {
  type?: Type9;
  payload: EnrichmentResultPayload;
  [k: string]: unknown;
}
/**
 * Payload for enrichment_result WS messages.
 * Contains enrichment metadata without full message history.
 */
export interface EnrichmentResultPayload {
  conversationId: Conversationid1;
  topics: Topics3;
  actions: Actions1;
  sentiment: Sentiment1;
  outcomes: Outcomes1;
  [k: string]: unknown;
}
/**
 * Broadcasted presence update to Bridge.
 */
export interface OutgoingOnlineUsersUpdateMsg {
  type?: Type10;
  payload: OutgoingOnlineUsersUpdatePayload;
  [k: string]: unknown;
}
/**
 * Presence heartbeat from Brain to Bridge.
 */
export interface OutgoingOnlineUsersUpdatePayload {
  user_ids: UserIds;
  timestamp: Timestamp;
  [k: string]: unknown;
}


// Discriminated union for all WS outgoing messages
export type OutgoingWssMessage =
  | ConnectionAckMsg
  | SystemStatusMsg
  | SystemErrorMsg
  | FullSyncResponseMsg
  | AppendMessageMsg
  | AnalyticsUpdateMsg
  | CommandToExecuteMsg
  | EnrichmentResultMsg
  | OutgoingOnlineUsersUpdateMsg;
