/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/insights/api/v1/insights/topics": {
    /**
     * Get Topic Metrics
     * @description Get volume, percentage of total, and trend for each topic over the given date range.
     */
    get: operations["getTopics"];
  };
  "/api/insights/api/v1/insights/sentiment-trend": {
    /**
     * Get Sentiment Trend
     * @description Get average sentiment score trend over time for conversations in the given date range.
     */
    get: operations["getSentimentTrend"];
  };
  "/api/insights/api/v1/insights/response-time": {
    /**
     * Get Response Time Metrics
     * @description Get average handling time (AHT), silence percentage, and turns metrics over the given date range.
     */
    get: operations["getResponseTimeMetrics"];
  };
  "/api/insights/api/v1/insights/full": {
    /**
     * Get Full Analytics
     * @description Get the complete analytics update payload, including topics, sentiment trend,
     * response time metrics, and per-conversation priorityScores/unreadCounts.
     */
    get: operations["getFullAnalytics"];
  };
  "/api/v1/schemas/wss": {
    /**
     * Get Wss Schema
     * @description Returns the JSON schema for OutgoingWssMessage.
     *
     * Frontend tooling uses this to auto-generate TypeScript WS types.
     * This ensures strict type safety between backend WS payloads
     * and frontend consumers.
     *
     * Example usage in frontend:
     *     $ curl http://localhost:8000/api/v1/schemas/wss > wss-schema.json
     *     $ json-schema-to-typescript wss-schema.json > ws-types.ts
     */
    get: operations["getWssSchema"];
  };
  "/": {
    /** Serve Frontend */
    get: operations["serveFrontend"];
  };
  "/api/v1/frontend/bootstrap/{user_id}": {
    /**
     * Bootstrap State
     * @description Returns the latest snapshot for a given user_id from DB.
     * Used by the frontend to hydrate state immediately after page load.
     */
    get: operations["bootstrapFrontendState"];
  };
  "/health": {
    /**
     * Health Check
     * @description Simple health check endpoint.
     */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AnalyticsUpdate
     * @description Granular update to analytics metrics.
     * Used for both snapshot and delta WS payloads.
     */
    AnalyticsUpdate: {
      /** Topics */
      topics: components["schemas"]["TopicMetricsResponse"][];
      sentiment_trend: components["schemas"]["SentimentTrendResponse"];
      response_time_metrics: components["schemas"]["ResponseTimeMetricsResponse"];
      /** Priorityscores */
      priorityScores?: {
        [key: string]: number;
      } | null;
      /** Unreadcounts */
      unreadCounts?: {
        [key: string]: number;
      } | null;
    };
    /** AvatarThumbs */
    AvatarThumbs: {
      /** C50 */
      c50?: string | null;
      /** C144 */
      c144?: string | null;
    };
    /**
     * EngagementAction
     * @description Represents an engagement action vertex in the LPG.
     */
    EngagementAction: {
      /** Actionid */
      actionId: string;
      /** Name */
      name: string;
      /** Embedding */
      embedding: number[];
      /** Type */
      type?: string | null;
    };
    /**
     * ExtendedConversationNode
     * @description Extended ConversationNode including additional frontend/UI and prioritization fields.
     *
     * Used in WS payloads when the frontend requires richer context,
     * such as displaying the other participant's profile or ranking conversations.
     */
    ExtendedConversationNode: {
      /** Conversationid */
      conversationId: string;
      /**
       * Startdate
       * Format: date-time
       */
      startDate: string;
      /** Enddate */
      endDate?: string | null;
      /** Messagecount */
      messageCount: number;
      /** Averageresponsetime */
      averageResponseTime?: number | null;
      /** Turns */
      turns?: number | null;
      /** Silencepercentage */
      silencePercentage?: number | null;
      /** Messages */
      messages?: components["schemas"]["Message"][] | null;
      /** Topics */
      topics?: components["schemas"]["Topic"][] | null;
      /** Actions */
      actions?: components["schemas"]["EngagementAction"][] | null;
      /** Sentiment */
      sentiment?: number | null;
      /** Outcomes */
      outcomes?: components["schemas"]["InteractionOutcome"][] | null;
      /** Priorityscore */
      priorityScore?: number | null;
      withUser?: components["schemas"]["UserRef"] | null;
    };
    /**
     * FullSyncResponse
     * @description Complete snapshot of all conversations, analytics, and graph data.
     * Sent once after processing a cache_update (snapshot ingestion).
     */
    FullSyncResponse: {
      /** Conversations */
      conversations: components["schemas"]["ExtendedConversationNode"][];
      analytics: components["schemas"]["AnalyticsUpdate"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HeaderSize */
    HeaderSize: {
      /** Width */
      width?: number | null;
      /** Height */
      height?: number | null;
    };
    /** HeaderThumbs */
    HeaderThumbs: {
      /** W480 */
      w480?: string | null;
      /** W760 */
      w760?: string | null;
    };
    /**
     * InteractionOutcome
     * @description Represents an interaction outcome vertex in the LPG.
     */
    InteractionOutcome: {
      /** Outcomeid */
      outcomeId: string;
      /** Name */
      name: string;
      /** Score */
      score?: number | null;
      /** Date */
      date?: string | null;
    };
    /** MediaFile */
    MediaFile: {
      /** Height */
      height?: number | null;
      /** Size */
      size?: number | null;
      /** Sources */
      sources?: string[] | null;
      /** Url */
      url?: string | null;
      /** Width */
      width?: number | null;
    };
    /** MediaItem */
    MediaItem: {
      /** Canview */
      canView?: boolean | null;
      /** Convertedtovideo */
      convertedToVideo?: boolean | null;
      /** Createdat */
      createdAt?: string | null;
      /** Duration */
      duration?: number | null;
      /** Files */
      files?: {
        [key: string]: components["schemas"]["MediaFile"];
      } | null;
      preview?: components["schemas"]["MediaPreview"] | null;
      /** Squarepreview */
      squarePreview?: {
        [key: string]: unknown;
      } | null;
      /** Thumb */
      thumb?: {
        [key: string]: unknown;
      } | null;
      /** Hascustompreview */
      hasCustomPreview?: boolean | null;
      /** Haserror */
      hasError?: boolean | null;
      /** Id */
      id?: number | string | null;
      /** Isready */
      isReady?: boolean | null;
      /** Type */
      type?: string | null;
      /** Videosources */
      videoSources?: ({
        [key: string]: string | null;
      }) | null;
    };
    /** MediaPreview */
    MediaPreview: {
      /** Height */
      height?: number | null;
      /** Size */
      size?: number | null;
      /** Url */
      url?: string | null;
      /** Width */
      width?: number | null;
    };
    /**
     * Message
     * @description Represents a single OnlyFans chat message, optionally enriched.
     */
    Message: {
      /** Id */
      id: number | string;
      /** Chat Id */
      chat_id?: number | string | null;
      /** Text */
      text?: string | null;
      /** Createdat */
      createdAt?: string | null;
      /** Created At */
      created_at?: string | null;
      /** Changedat */
      changedAt?: string | null;
      fromUser?: components["schemas"]["UserRef"] | null;
      /** Is Creator */
      is_creator?: boolean | null;
      /**
       * Sentimentscore
       * @description Sentiment score between 0 and 1
       */
      sentimentScore?: number | null;
      /**
       * Topics
       * @description List of NLP-extracted topics
       */
      topics?: string[] | null;
      /** Is Inbound */
      is_inbound?: boolean | null;
      /** Ispinned */
      isPinned?: boolean | null;
      /** Istip */
      isTip?: boolean | null;
      /** Isliked */
      isLiked?: boolean | null;
      /** Isfree */
      isFree?: boolean | null;
      /** Iscouplepeoplemedia */
      isCouplePeopleMedia?: boolean | null;
      /** Ismarkdowndisabled */
      isMarkdownDisabled?: boolean | null;
      /** Ismediaready */
      isMediaReady?: boolean | null;
      /** Isnew */
      isNew?: boolean | null;
      /** Isopened */
      isOpened?: boolean | null;
      /** Isreportedbyme */
      isReportedByMe?: boolean | null;
      /** Isfromqueue */
      isFromQueue?: boolean | null;
      /** Canbepinned */
      canBePinned?: boolean | null;
      /** Canpurchase */
      canPurchase?: boolean | null;
      /** Canpurchasereason */
      canPurchaseReason?: string | null;
      /** Canreport */
      canReport?: boolean | null;
      /** Canunsendqueue */
      canUnsendQueue?: boolean | null;
      /** Mediacount */
      mediaCount?: number | null;
      /** Price */
      price?: number | null;
      /** Cancelseconds */
      cancelSeconds?: number | null;
      /** Queueid */
      queueId?: number | string | null;
      /** Unsendsecondsqueue */
      unsendSecondsQueue?: number | null;
      /** Giphyid */
      giphyId?: string | null;
      /** Lockedtext */
      lockedText?: boolean | null;
      /** Responsetype */
      responseType?: string | null;
      /** Media */
      media?: components["schemas"]["MediaItem"][] | null;
      /** Previews */
      previews?: {
          [key: string]: unknown;
        }[] | null;
      /** Releaseforms */
      releaseForms?: {
          [key: string]: unknown;
        }[] | null;
      replyToMessage?: components["schemas"]["Message"] | null;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      };
    };
    /**
     * ResponseTimeMetricsResponse
     * @description Metrics related to response times and conversation turns.
     */
    ResponseTimeMetricsResponse: {
      /** Average Handling Time Minutes */
      average_handling_time_minutes: number;
      /** Silence Percentage */
      silence_percentage: number;
      /** Turns */
      turns: number;
    };
    /**
     * SentimentTrendPoint
     * @description Represents a single point in a sentiment trend timeline.
     */
    SentimentTrendPoint: {
      /**
       * Date
       * Format: date-time
       */
      date: string;
      /** Sentiment Score */
      sentiment_score: number;
    };
    /**
     * SentimentTrendResponse
     * @description Time series of sentiment scores.
     */
    SentimentTrendResponse: {
      /** Trend */
      trend: components["schemas"]["SentimentTrendPoint"][];
    };
    /**
     * Topic
     * @description Represents a topic vertex in the LPG.
     */
    Topic: {
      /** Topicid */
      topicId: string;
      /** Description */
      description: string;
      /** Embedding */
      embedding: number[];
      /** Category */
      category?: string | null;
    };
    /**
     * TopicMetricsResponse
     * @description Aggregated metrics for a specific topic.
     */
    TopicMetricsResponse: {
      /** Topic */
      topic: string;
      /** Volume */
      volume: number;
      /** Percentage Of Total */
      percentage_of_total: number;
      /** Trend */
      trend?: number | null;
    };
    /**
     * UserRef
     * @description Minimal OnlyFans user reference with optional extended profile fields.
     */
    UserRef: {
      /** Id */
      id?: number | string | null;
      /** View */
      view?: string | null;
      /** Name */
      name?: string | null;
      /** Username */
      username?: string | null;
      /** Displayname */
      displayName?: string | null;
      /** Avatar */
      avatar?: string | null;
      avatarThumbs?: components["schemas"]["AvatarThumbs"] | null;
      /** Header */
      header?: string | null;
      headerSize?: components["schemas"]["HeaderSize"] | null;
      headerThumbs?: components["schemas"]["HeaderThumbs"] | null;
      /** Lastseen */
      lastSeen?: string | null;
      /** Notice */
      notice?: string | null;
      /** Canaddsubscriber */
      canAddSubscriber?: boolean | null;
      /** Cancommentstory */
      canCommentStory?: boolean | null;
      /** Canearn */
      canEarn?: boolean | null;
      /** Canlookstory */
      canLookStory?: boolean | null;
      /** Canpayinternal */
      canPayInternal?: boolean | null;
      /** Canrestrict */
      canRestrict?: boolean | null;
      /** Currentsubscribeprice */
      currentSubscribePrice?: number | null;
      /** Hasnotviewedstory */
      hasNotViewedStory?: boolean | null;
      /** Hasscheduledstream */
      hasScheduledStream?: boolean | null;
      /** Hasstories */
      hasStories?: boolean | null;
      /** Hasstream */
      hasStream?: boolean | null;
      /** Ispaywallrequired */
      isPaywallRequired?: boolean | null;
      /** Isrestricted */
      isRestricted?: boolean | null;
      /** Isverified */
      isVerified?: boolean | null;
      /** Listsstates */
      listsStates?: {
          [key: string]: unknown;
        }[] | null;
      /** Showmediacount */
      showMediaCount?: boolean | null;
      /** Subscribeprice */
      subscribePrice?: number | null;
      /** Subscribedby */
      subscribedBy?: boolean | null;
      /** Subscribedbyautoprolong */
      subscribedByAutoprolong?: boolean | null;
      /** Subscribedbyexpire */
      subscribedByExpire?: boolean | null;
      /** Subscribedbyexpiredate */
      subscribedByExpireDate?: string | null;
      /** Subscribedisexpirednow */
      subscribedIsExpiredNow?: boolean | null;
      /** Subscribedon */
      subscribedOn?: boolean | null;
      /** Subscribedonduration */
      subscribedOnDuration?: string | null;
      /** Subscribedonexpirednow */
      subscribedOnExpiredNow?: boolean | null;
      /** Subscriptionbundles */
      subscriptionBundles?: {
          [key: string]: unknown;
        }[] | null;
      /** Tipsenabled */
      tipsEnabled?: boolean | null;
      /** Tipsmax */
      tipsMax?: number | null;
      /** Tipsmin */
      tipsMin?: number | null;
      /** Tipsmininternal */
      tipsMinInternal?: number | null;
      /** Tipstextenabled */
      tipsTextEnabled?: boolean | null;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Topic Metrics
   * @description Get volume, percentage of total, and trend for each topic over the given date range.
   */
  getTopics: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
        /** @description Filter metrics for a specific creator */
        creator_id?: string | null;
        /** @description If true, broadcast analytics update via WS */
        broadcast?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TopicMetricsResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Sentiment Trend
   * @description Get average sentiment score trend over time for conversations in the given date range.
   */
  getSentimentTrend: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
        creator_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SentimentTrendResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Response Time Metrics
   * @description Get average handling time (AHT), silence percentage, and turns metrics over the given date range.
   */
  getResponseTimeMetrics: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
        creator_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResponseTimeMetricsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Full Analytics
   * @description Get the complete analytics update payload, including topics, sentiment trend,
   * response time metrics, and per-conversation priorityScores/unreadCounts.
   */
  getFullAnalytics: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
        creator_id?: string | null;
        /** @description If true, also broadcast via WS */
        broadcast?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AnalyticsUpdate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Wss Schema
   * @description Returns the JSON schema for OutgoingWssMessage.
   *
   * Frontend tooling uses this to auto-generate TypeScript WS types.
   * This ensures strict type safety between backend WS payloads
   * and frontend consumers.
   *
   * Example usage in frontend:
   *     $ curl http://localhost:8000/api/v1/schemas/wss > wss-schema.json
   *     $ json-schema-to-typescript wss-schema.json > ws-types.ts
   */
  getWssSchema: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Serve Frontend */
  serveFrontend: {
    parameters: {
      query?: {
        /** @description User ID (must match extension connection) */
        user_id?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/html": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bootstrap State
   * @description Returns the latest snapshot for a given user_id from DB.
   * Used by the frontend to hydrate state immediately after page load.
   */
  bootstrapFrontendState: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FullSyncResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health Check
   * @description Simple health check endpoint.
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}


// Named exports for schemas
export type AnalyticsUpdate = components["schemas"]["AnalyticsUpdate"];
export type AvatarThumbs = components["schemas"]["AvatarThumbs"];
export type EngagementAction = components["schemas"]["EngagementAction"];
export type ExtendedConversationNode = components["schemas"]["ExtendedConversationNode"];
export type FullSyncResponse = components["schemas"]["FullSyncResponse"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HeaderSize = components["schemas"]["HeaderSize"];
export type HeaderThumbs = components["schemas"]["HeaderThumbs"];
export type InteractionOutcome = components["schemas"]["InteractionOutcome"];
export type MediaFile = components["schemas"]["MediaFile"];
export type MediaItem = components["schemas"]["MediaItem"];
export type MediaPreview = components["schemas"]["MediaPreview"];
export type Message = components["schemas"]["Message"];
export type ResponseTimeMetricsResponse = components["schemas"]["ResponseTimeMetricsResponse"];
export type SentimentTrendPoint = components["schemas"]["SentimentTrendPoint"];
export type SentimentTrendResponse = components["schemas"]["SentimentTrendResponse"];
export type Topic = components["schemas"]["Topic"];
export type TopicMetricsResponse = components["schemas"]["TopicMetricsResponse"];
export type UserRef = components["schemas"]["UserRef"];
export type ValidationError = components["schemas"]["ValidationError"];
