/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/conversations/chats": {
    /**
     * Fetch Chats
     * @description Fetch chat threads from OnlyFans API or cache.
     *
     * Args:
     *     auth (AuthData): Authentication payload containing session cookies.
     *     limit (int): Max number of chats to return.
     *     offset (int): Pagination offset.
     *
     * Returns:
     *     List[ChatThread]: Validated chat thread models.
     */
    post: operations["fetch_chats_api_conversations_chats_post"];
  };
  "/api/conversations/chats/{chat_id}/messages": {
    /**
     * Fetch Messages
     * @description Fetch messages for a specific chat thread.
     *
     * Args:
     *     chat_id (str|int): The chat ID to fetch messages from.
     *     auth (AuthData): Authentication payload containing session cookies.
     *     limit (int): Max number of messages to return.
     *     offset (int): Pagination offset.
     *
     * Returns:
     *     List[Message]: Validated message models.
     */
    post: operations["fetch_messages_api_conversations_chats__chat_id__messages_post"];
  };
  "/api/conversations/chats/{chat_id}/full": {
    /**
     * Fetch Chat With Messages
     * @description Fetch a chat thread along with its messages.
     *
     * Args:
     *     chat_id (str|int): The chat ID to fetch.
     *     auth (AuthData): Authentication payload containing session cookies.
     *     message_limit (int): Max number of messages to include.
     *
     * Returns:
     *     ChatThread: Validated chat thread model with messages.
     */
    post: operations["fetch_chat_with_messages_api_conversations_chats__chat_id__full_post"];
  };
  "/api/conversations/from-extension": {
    /**
     * Ingest From Extension
     * @description Accept a raw IndexedDB dump from the browser extension and convert to typed models.
     *
     * Expected payload format:
     * {
     *     "chats": [...],
     *     "messages": [...]
     * }
     *
     * Also runs enrichment + graph build for each conversation.
     *
     * Returns:
     *     SyncResponse: Validated chats and messages from payload.
     */
    post: operations["ingest_from_extension_api_conversations_from_extension_post"];
  };
  "/api/conversations/extension-cache": {
    /**
     * Update Cache
     * @description Update backend's cache with raw dict data from the frontend or WS.
     *
     * Args:
     *     payload (dict): Contains 'chats' and 'messages' lists.
     *
     * Returns:
     *     dict: Status and counts of updated records.
     */
    post: operations["update_cache_api_conversations_extension_cache_post"];
  };
  "/api/conversations/sync": {
    /**
     * Sync From Cache
     * @description Return the current chats/messages from the cache as validated Pydantic models.
     *
     * Allows frontend to fetch initial data before WS updates.
     *
     * Returns:
     *     SyncResponse: Cached chats and messages.
     */
    get: operations["sync_from_cache_api_conversations_sync_get"];
  };
  "/api/insights/topics": {
    /**
     * Get Topic Metrics
     * @description Get volume, percentage of total, and trend for each topic over the given date range.
     */
    get: operations["get_topic_metrics_api_insights_topics_get"];
  };
  "/api/insights/sentiment-trend": {
    /**
     * Get Sentiment Trend
     * @description Get average sentiment score trend over time for conversations in the given date range.
     */
    get: operations["get_sentiment_trend_api_insights_sentiment_trend_get"];
  };
  "/api/insights/response-time": {
    /**
     * Get Response Time Metrics
     * @description Get average handling time (AHT), silence percentage, and turns metrics over the given date range.
     */
    get: operations["get_response_time_metrics_api_insights_response_time_get"];
  };
  "/": {
    /**
     * Serve Frontend
     * @description Serve the frontend entry HTML, injecting runtime config for extension and WS.
     */
    get: operations["serve_frontend__get"];
  };
  "/health": {
    /**
     * Health Check
     * @description Simple health check endpoint.
     */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AuthData
     * @description Authentication data for OnlyFans API.
     * For extension-based ingestion, auth_cookie may be omitted.
     */
    AuthData: {
      /** Auth Cookie */
      auth_cookie?: string | null;
    };
    /** AvatarThumbs */
    AvatarThumbs: {
      /** C50 */
      c50?: string | null;
      /** C144 */
      c144?: string | null;
    };
    /** ChatThread */
    ChatThread: {
      /** Id */
      id: number | string;
      withUser?: components["schemas"]["UserRef"] | null;
      last_message?: components["schemas"]["Message"] | null;
      /** Unread Count */
      unread_count?: number | null;
      /** Unreadmessagescount */
      unreadMessagesCount?: number | null;
      /** Messages */
      messages?: components["schemas"]["Message"][] | null;
      /** Extra */
      extra?: Record<string, never>;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HeaderSize */
    HeaderSize: {
      /** Width */
      width?: number | null;
      /** Height */
      height?: number | null;
    };
    /** HeaderThumbs */
    HeaderThumbs: {
      /** W480 */
      w480?: string | null;
      /** W760 */
      w760?: string | null;
    };
    /** MediaFile */
    MediaFile: {
      /** Height */
      height?: number | null;
      /** Size */
      size?: number | null;
      /** Sources */
      sources?: string[] | null;
      /** Url */
      url?: string | null;
      /** Width */
      width?: number | null;
    };
    /** MediaItem */
    MediaItem: {
      /** Canview */
      canView?: boolean | null;
      /** Convertedtovideo */
      convertedToVideo?: boolean | null;
      /** Createdat */
      createdAt?: string | null;
      /** Duration */
      duration?: number | null;
      /** Files */
      files?: {
        [key: string]: components["schemas"]["MediaFile"];
      } | null;
      preview?: components["schemas"]["MediaPreview"] | null;
      /** Squarepreview */
      squarePreview?: Record<string, never> | null;
      /** Thumb */
      thumb?: Record<string, never> | null;
      /** Hascustompreview */
      hasCustomPreview?: boolean | null;
      /** Haserror */
      hasError?: boolean | null;
      /** Id */
      id?: number | string | null;
      /** Isready */
      isReady?: boolean | null;
      /** Type */
      type?: string | null;
      /** Videosources */
      videoSources?: ({
        [key: string]: string | null;
      }) | null;
    };
    /** MediaPreview */
    MediaPreview: {
      /** Height */
      height?: number | null;
      /** Size */
      size?: number | null;
      /** Url */
      url?: string | null;
      /** Width */
      width?: number | null;
    };
    /** Message */
    Message: {
      /** Id */
      id: number | string;
      /** Chat Id */
      chat_id?: number | string | null;
      /** Text */
      text?: string | null;
      /** Createdat */
      createdAt?: string | null;
      /** Created At */
      created_at?: string | null;
      /** Changedat */
      changedAt?: string | null;
      fromUser?: components["schemas"]["UserRef"] | null;
      /** Is Creator */
      is_creator?: boolean | null;
      /** Is Inbound */
      is_inbound?: boolean | null;
      /** Ispinned */
      isPinned?: boolean | null;
      /** Istip */
      isTip?: boolean | null;
      /** Isliked */
      isLiked?: boolean | null;
      /** Isfree */
      isFree?: boolean | null;
      /** Iscouplepeoplemedia */
      isCouplePeopleMedia?: boolean | null;
      /** Ismarkdowndisabled */
      isMarkdownDisabled?: boolean | null;
      /** Ismediaready */
      isMediaReady?: boolean | null;
      /** Isnew */
      isNew?: boolean | null;
      /** Isopened */
      isOpened?: boolean | null;
      /** Isreportedbyme */
      isReportedByMe?: boolean | null;
      /** Isfromqueue */
      isFromQueue?: boolean | null;
      /** Canbepinned */
      canBePinned?: boolean | null;
      /** Canpurchase */
      canPurchase?: boolean | null;
      /** Canpurchasereason */
      canPurchaseReason?: string | null;
      /** Canreport */
      canReport?: boolean | null;
      /** Canunsendqueue */
      canUnsendQueue?: boolean | null;
      /** Mediacount */
      mediaCount?: number | null;
      /** Price */
      price?: number | null;
      /** Cancelseconds */
      cancelSeconds?: number | null;
      /** Queueid */
      queueId?: number | string | null;
      /** Unsendsecondsqueue */
      unsendSecondsQueue?: number | null;
      /** Giphyid */
      giphyId?: string | null;
      /** Lockedtext */
      lockedText?: boolean | null;
      /** Responsetype */
      responseType?: string | null;
      /** Media */
      media?: components["schemas"]["MediaItem"][] | null;
      /** Previews */
      previews?: Record<string, never>[] | null;
      /** Releaseforms */
      releaseForms?: Record<string, never>[] | null;
      replyToMessage?: components["schemas"]["Message"] | null;
      /** Extra */
      extra?: Record<string, never>;
    };
    /** ResponseTimeMetricsResponse */
    ResponseTimeMetricsResponse: {
      /** Average Handling Time Minutes */
      average_handling_time_minutes: number;
      /** Silence Percentage */
      silence_percentage: number;
      /** Turns */
      turns: number;
    };
    /** SentimentTrendPoint */
    SentimentTrendPoint: {
      /**
       * Date
       * Format: date-time
       */
      date: string;
      /** Sentiment Score */
      sentiment_score: number;
    };
    /** SentimentTrendResponse */
    SentimentTrendResponse: {
      /** Trend */
      trend: components["schemas"]["SentimentTrendPoint"][];
    };
    /** SyncResponse */
    SyncResponse: {
      /** Chats */
      chats: components["schemas"]["ChatThread"][];
      /** Messages */
      messages: components["schemas"]["Message"][];
    };
    /** TopicMetricsResponse */
    TopicMetricsResponse: {
      /** Topic */
      topic: string;
      /** Volume */
      volume: number;
      /** Percentage Of Total */
      percentage_of_total: number;
      /** Trend */
      trend?: number | null;
    };
    /** UserRef */
    UserRef: {
      /** Id */
      id?: number | string | null;
      /** View */
      view?: string | null;
      /** Name */
      name?: string | null;
      /** Username */
      username?: string | null;
      /** Displayname */
      displayName?: string | null;
      /** Avatar */
      avatar?: string | null;
      avatarThumbs?: components["schemas"]["AvatarThumbs"] | null;
      /** Header */
      header?: string | null;
      headerSize?: components["schemas"]["HeaderSize"] | null;
      headerThumbs?: components["schemas"]["HeaderThumbs"] | null;
      /** Lastseen */
      lastSeen?: string | null;
      /** Notice */
      notice?: string | null;
      /** Canaddsubscriber */
      canAddSubscriber?: boolean | null;
      /** Cancommentstory */
      canCommentStory?: boolean | null;
      /** Canearn */
      canEarn?: boolean | null;
      /** Canlookstory */
      canLookStory?: boolean | null;
      /** Canpayinternal */
      canPayInternal?: boolean | null;
      /** Canrestrict */
      canRestrict?: boolean | null;
      /** Currentsubscribeprice */
      currentSubscribePrice?: number | null;
      /** Hasnotviewedstory */
      hasNotViewedStory?: boolean | null;
      /** Hasscheduledstream */
      hasScheduledStream?: boolean | null;
      /** Hasstories */
      hasStories?: boolean | null;
      /** Hasstream */
      hasStream?: boolean | null;
      /** Ispaywallrequired */
      isPaywallRequired?: boolean | null;
      /** Isrestricted */
      isRestricted?: boolean | null;
      /** Isverified */
      isVerified?: boolean | null;
      /** Listsstates */
      listsStates?: Record<string, never>[] | null;
      /** Showmediacount */
      showMediaCount?: boolean | null;
      /** Subscribeprice */
      subscribePrice?: number | null;
      /** Subscribedby */
      subscribedBy?: boolean | null;
      /** Subscribedbyautoprolong */
      subscribedByAutoprolong?: boolean | null;
      /** Subscribedbyexpire */
      subscribedByExpire?: boolean | null;
      /** Subscribedbyexpiredate */
      subscribedByExpireDate?: string | null;
      /** Subscribedisexpirednow */
      subscribedIsExpiredNow?: boolean | null;
      /** Subscribedon */
      subscribedOn?: boolean | null;
      /** Subscribedonduration */
      subscribedOnDuration?: string | null;
      /** Subscribedonexpirednow */
      subscribedOnExpiredNow?: boolean | null;
      /** Subscriptionbundles */
      subscriptionBundles?: Record<string, never>[] | null;
      /** Tipsenabled */
      tipsEnabled?: boolean | null;
      /** Tipsmax */
      tipsMax?: number | null;
      /** Tipsmin */
      tipsMin?: number | null;
      /** Tipsmininternal */
      tipsMinInternal?: number | null;
      /** Tipstextenabled */
      tipsTextEnabled?: boolean | null;
      /** Extra */
      extra?: Record<string, never>;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Fetch Chats
   * @description Fetch chat threads from OnlyFans API or cache.
   *
   * Args:
   *     auth (AuthData): Authentication payload containing session cookies.
   *     limit (int): Max number of chats to return.
   *     offset (int): Pagination offset.
   *
   * Returns:
   *     List[ChatThread]: Validated chat thread models.
   */
  fetch_chats_api_conversations_chats_post: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthData"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatThread"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Fetch Messages
   * @description Fetch messages for a specific chat thread.
   *
   * Args:
   *     chat_id (str|int): The chat ID to fetch messages from.
   *     auth (AuthData): Authentication payload containing session cookies.
   *     limit (int): Max number of messages to return.
   *     offset (int): Pagination offset.
   *
   * Returns:
   *     List[Message]: Validated message models.
   */
  fetch_messages_api_conversations_chats__chat_id__messages_post: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        chat_id: number | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthData"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Fetch Chat With Messages
   * @description Fetch a chat thread along with its messages.
   *
   * Args:
   *     chat_id (str|int): The chat ID to fetch.
   *     auth (AuthData): Authentication payload containing session cookies.
   *     message_limit (int): Max number of messages to include.
   *
   * Returns:
   *     ChatThread: Validated chat thread model with messages.
   */
  fetch_chat_with_messages_api_conversations_chats__chat_id__full_post: {
    parameters: {
      query?: {
        message_limit?: number;
      };
      path: {
        chat_id: number | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthData"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatThread"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Ingest From Extension
   * @description Accept a raw IndexedDB dump from the browser extension and convert to typed models.
   *
   * Expected payload format:
   * {
   *     "chats": [...],
   *     "messages": [...]
   * }
   *
   * Also runs enrichment + graph build for each conversation.
   *
   * Returns:
   *     SyncResponse: Validated chats and messages from payload.
   */
  ingest_from_extension_api_conversations_from_extension_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Cache
   * @description Update backend's cache with raw dict data from the frontend or WS.
   *
   * Args:
   *     payload (dict): Contains 'chats' and 'messages' lists.
   *
   * Returns:
   *     dict: Status and counts of updated records.
   */
  update_cache_api_conversations_extension_cache_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Sync From Cache
   * @description Return the current chats/messages from the cache as validated Pydantic models.
   *
   * Allows frontend to fetch initial data before WS updates.
   *
   * Returns:
   *     SyncResponse: Cached chats and messages.
   */
  sync_from_cache_api_conversations_sync_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
    };
  };
  /**
   * Get Topic Metrics
   * @description Get volume, percentage of total, and trend for each topic over the given date range.
   */
  get_topic_metrics_api_insights_topics_get: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TopicMetricsResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Sentiment Trend
   * @description Get average sentiment score trend over time for conversations in the given date range.
   */
  get_sentiment_trend_api_insights_sentiment_trend_get: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SentimentTrendResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Response Time Metrics
   * @description Get average handling time (AHT), silence percentage, and turns metrics over the given date range.
   */
  get_response_time_metrics_api_insights_response_time_get: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResponseTimeMetricsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Serve Frontend
   * @description Serve the frontend entry HTML, injecting runtime config for extension and WS.
   */
  serve_frontend__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/html": string;
        };
      };
    };
  };
  /**
   * Health Check
   * @description Simple health check endpoint.
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}


// Named exports for schemas
export type AuthData = components["schemas"]["AuthData"];
export type AvatarThumbs = components["schemas"]["AvatarThumbs"];
export type ChatThread = components["schemas"]["ChatThread"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HeaderSize = components["schemas"]["HeaderSize"];
export type HeaderThumbs = components["schemas"]["HeaderThumbs"];
export type MediaFile = components["schemas"]["MediaFile"];
export type MediaItem = components["schemas"]["MediaItem"];
export type MediaPreview = components["schemas"]["MediaPreview"];
export type Message = components["schemas"]["Message"];
export type ResponseTimeMetricsResponse = components["schemas"]["ResponseTimeMetricsResponse"];
export type SentimentTrendPoint = components["schemas"]["SentimentTrendPoint"];
export type SentimentTrendResponse = components["schemas"]["SentimentTrendResponse"];
export type SyncResponse = components["schemas"]["SyncResponse"];
export type TopicMetricsResponse = components["schemas"]["TopicMetricsResponse"];
export type UserRef = components["schemas"]["UserRef"];
export type ValidationError = components["schemas"]["ValidationError"];
