import test from 'node:test'; import assert from 'node:assert/strict';
import { loadWasm } from './helpers.mjs'; import { NoiseSession, SessionFailure } from '../web/noise-session.mjs'; import { receiptBinding, spikePrologue, fromHex } from '../web/noise-binding.mjs';
import { FIXED_CLAIMS, AGENT_PRIVATE_HEX, AGENT_PUBLIC_HEX, BRAIN_PRIVATE_HEX, BRAIN_PUBLIC_HEX } from '../web/fixture.mjs';
async function pair({bindingA,bindingB,wrongPin=false, timeoutMs=2000, signal}={}) { const SnowSession=await loadWasm(); const binding=await receiptBinding(FIXED_CLAIMS); const a=new NoiseSession({SnowSession,initiator:true,localPrivateKey:fromHex(AGENT_PRIVATE_HEX),remotePublicKey:fromHex(wrongPin?AGENT_PUBLIC_HEX:BRAIN_PUBLIC_HEX),prologue:spikePrologue(bindingA??binding),timeoutMs,signal}); const b=new NoiseSession({SnowSession,initiator:false,localPrivateKey:fromHex(BRAIN_PRIVATE_HEX),remotePublicKey:fromHex(AGENT_PUBLIC_HEX),prologue:spikePrologue(bindingB??binding),timeoutMs}); return [a,b]; }
function ready(a,b){ const m1=a.writeHandshake(); b.readHandshake(m1); const m2=b.writeHandshake(); a.readHandshake(m2); a.finishHandshake(); b.finishHandshake(); const c=a.writeConfirmation(); b.readConfirmation(c); const d=b.writeConfirmation(); a.readConfirmation(d); return {m1,m2}; }
function throwsCode(fn, code){ assert.throws(fn, e=>e instanceof SessionFailure && e.code===code); }
test('wrong pin, wrong binding, and tampered handshake fail closed',async()=>{ let [a,b]=await pair({wrongPin:true}); throwsCode(()=>b.readHandshake(a.writeHandshake()),'handshake_failed'); const x=(await receiptBinding({...FIXED_CLAIMS,jti:'09'.repeat(32)})); [a,b]=await pair({bindingB:x}); throwsCode(()=>b.readHandshake(a.writeHandshake()),'handshake_failed'); [a,b]=await pair(); const m=a.writeHandshake(); m[m.length-1]^=1; throwsCode(()=>b.readHandshake(m),'handshake_failed'); });
test('replay, reorder, tamper, cross-session ciphertext fail closed',async()=>{ for(const kind of ['replay','reorder','tamper','cross']) { const [a,b]=await pair(); ready(a,b); const first=a.seal(new Uint8Array([1])); let frame; if(kind==='replay'){ b.open(first); frame=first; } else if(kind==='reorder'){ frame=a.seal(new Uint8Array([2])); } else if(kind==='tamper'){ frame=first.slice(); frame.at(-1); frame[frame.length-1]^=1; } else { const [x,y]=await pair(); ready(x,y); frame=x.seal(new Uint8Array([9])); } throwsCode(()=>b.open(frame),'authentication_failed'); assert.equal(b.state,'closed'); } });
test('application before confirmation, oversized input, cancellation, deadline are refused',async()=>{ let [a,b]=await pair(); const m1=a.writeHandshake(); b.readHandshake(m1); const m2=b.writeHandshake(); a.readHandshake(m2); a.finishHandshake(); b.finishHandshake(); throwsCode(()=>a.seal(new Uint8Array([1])),'unexpected_state'); [a]=await pair(); throwsCode(()=>a.readHandshake(new Uint8Array(4097)),'invalid_frame'); const ac=new AbortController(); [a]=await pair({signal:ac.signal}); ac.abort(); throwsCode(()=>a.writeHandshake(),'session_closed'); [a]=await pair({timeoutMs:5}); await new Promise(r=>setTimeout(r,15)); throwsCode(()=>a.writeHandshake(),'session_closed'); });
test('fresh reconnect gets fresh ephemeral state',async()=>{ const [a]=await pair(); const m1=a.writeHandshake(); a.close(); const [b]=await pair(); const m2=b.writeHandshake(); assert.notDeepEqual(m1,m2); });
