import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

const filename = fileURLToPath(import.meta.url);
const themeDirectory = path.dirname(filename);
const sourcePath = path.join(themeDirectory, 'tokens.json');
const generatedPath = path.join(themeDirectory, 'generated', 'tokens.ts');
const staticTokensPath = path.join(themeDirectory, 'generated', 'static-tokens.css');
const header =
  '// AUTO-GENERATED FROM src/theme/tokens.json.\n// DO NOT EDIT THIS FILE DIRECTLY.\n\n';

function isObject(value: JsonValue | undefined): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function readPath(root: JsonObject, tokenPath: string): JsonValue {
  let value: JsonValue = root;
  for (const segment of tokenPath.split('.')) {
    if (!isObject(value) || !(segment in value)) {
      throw new Error('Unknown token reference: {' + tokenPath + '}');
    }
    value = value[segment];
  }
  return value;
}

function resolveValue(value: JsonValue, root: JsonObject, stack: string[] = []): JsonValue {
  if (typeof value === 'string') {
    const reference = /^\{([^}]+)\}$/.exec(value);
    if (!reference) return value;
    const tokenPath = reference[1];
    if (stack.includes(tokenPath)) {
      throw new Error('Circular token reference: ' + [...stack, tokenPath].join(' -> '));
    }
    return resolveValue(readPath(root, tokenPath), root, [...stack, tokenPath]);
  }
  if (Array.isArray(value)) return value.map((entry) => resolveValue(entry, root, stack));
  if (!isObject(value)) return value;

  return Object.fromEntries(
    Object.keys(value)
      .filter((key) => !key.startsWith('_'))
      .sort()
      .map((key) => [key, resolveValue(value[key], root, stack)]),
  );
}

function stableStringify(value: JsonValue): string {
  const normalize = (entry: JsonValue): JsonValue => {
    if (Array.isArray(entry)) return entry.map(normalize);
    if (!isObject(entry)) return entry;
    return Object.fromEntries(
      Object.keys(entry)
        .sort()
        .map((key) => [key, normalize(entry[key])]),
    );
  };
  return JSON.stringify(normalize(value), null, 2);
}

function getObject(parent: JsonObject, key: string): JsonObject {
  const value = parent[key];
  if (!isObject(value)) throw new Error('Expected token object at ' + key);
  return value;
}

function getString(parent: JsonObject, key: string): string {
  const value = parent[key];
  if (typeof value !== 'string') throw new Error('Expected string token at ' + key);
  return value;
}

type RgbColor = { r: number; g: number; b: number; a: number };

function parseColor(value: string): RgbColor {
  const hexMatch = /^#([0-9a-f]{6})$/i.exec(value);
  if (hexMatch) {
    const [r, g, b] = [0, 2, 4].map((offset) =>
      Number.parseInt(hexMatch[1].slice(offset, offset + 2), 16),
    );
    return { r, g, b, a: 1 };
  }
  const rgbaMatch =
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i.exec(value);
  if (rgbaMatch) {
    return {
      r: Number.parseFloat(rgbaMatch[1]),
      g: Number.parseFloat(rgbaMatch[2]),
      b: Number.parseFloat(rgbaMatch[3]),
      a: rgbaMatch[4] === undefined ? 1 : Number.parseFloat(rgbaMatch[4]),
    };
  }
  throw new Error('Contrast validation requires a hex or rgb(a) color, received ' + value);
}

// Composites a possibly-translucent color over an opaque backdrop before measuring.
function flattenOverBackground(value: string, backdropHex: string): { r: number; g: number; b: number } {
  const color = parseColor(value);
  if (color.a >= 1) return color;
  const backdrop = parseColor(backdropHex);
  return {
    r: color.a * color.r + (1 - color.a) * backdrop.r,
    g: color.a * color.g + (1 - color.a) * backdrop.g,
    b: color.a * color.b + (1 - color.a) * backdrop.b,
  };
}

function relativeLuminance({ r, g, b }: { r: number; g: number; b: number }): number {
  const [red, green, blue] = [r, g, b].map((channel) => {
    const normalized = channel / 255;
    return normalized <= 0.04045 ? normalized / 12.92 : ((normalized + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
}

// `backdrop` must resolve to an opaque surface; `foreground`/`backdrop` may be hex or rgb(a).
function contrastRatio(foreground: string, backdrop: string): number {
  const foregroundLuminance = relativeLuminance(flattenOverBackground(foreground, backdrop));
  const backdropLuminance = relativeLuminance(flattenOverBackground(backdrop, backdrop));
  const light = Math.max(foregroundLuminance, backdropLuminance);
  const dark = Math.min(foregroundLuminance, backdropLuminance);
  return (light + 0.05) / (dark + 0.05);
}

function requireRatio(
  ratio: number,
  minimum: number,
  schemeName: string,
  foregroundRole: string,
  surfaceRole: string,
): void {
  if (ratio < minimum) {
    throw new Error(
      schemeName +
        '.' +
        foregroundRole +
        ' on ' +
        surfaceRole +
        ' has ' +
        ratio.toFixed(2) +
        ':1 contrast, below the ' +
        minimum +
        ':1 minimum',
    );
  }
}

function validateContrast(colorSchemes: JsonObject): void {
  for (const schemeName of ['light', 'dark']) {
    const scheme = getObject(colorSchemes, schemeName);
    const text = getObject(scheme, 'text');
    const background = getObject(scheme, 'background');
    const surface = getObject(scheme, 'surface');
    const primary = getObject(scheme, 'primary');

    const backgroundDefault = getString(background, 'default');
    const backgroundPaper = getString(background, 'paper');
    const surfaceSubtle = getString(surface, 'subtle');
    const surfaceGlass = getString(surface, 'glass');
    // The AppBar renders its translucent glass surface over ambient page content;
    // background.default is used as the representative backdrop for that composite.
    const appBarComposite = flattenOverBackground(surfaceGlass, backgroundDefault);
    const appBarCompositeHex =
      '#' +
      [appBarComposite.r, appBarComposite.g, appBarComposite.b]
        .map((channel) => Math.round(channel).toString(16).padStart(2, '0'))
        .join('');

    const textSurfaces: Array<[string, string]> = [
      ['background.default', backgroundDefault],
      ['background.paper', backgroundPaper],
      ['surface.subtle', surfaceSubtle],
      ['surface.glass (AppBar composite)', appBarCompositeHex],
    ];
    const textForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
      ...(('muted' in text ? [['text.muted', getString(text, 'muted')]] : []) as Array<
        [string, string]
      >),
    ];
    for (const [foregroundRole, foreground] of textForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of textSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Feedback foregrounds are checked against background.default and background.paper.
    const feedbackForegroundRoles: Array<[string, string]> = [
      ['success.main', getString(getObject(scheme, 'success'), 'main')],
      ['warning.main', getString(getObject(scheme, 'warning'), 'main')],
      ['error.main', getString(getObject(scheme, 'error'), 'main')],
    ];
    for (const [foregroundRole, foreground] of feedbackForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of [
        ['background.default', backgroundDefault],
        ['background.paper', backgroundPaper],
      ] as Array<[string, string]>) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Message bubbles render body text (text.primary) and metadata (text.secondary)
    // on their own opaque surfaces; links inherit the body color, so no separate link
    // role is measured. Both surfaces are validated in both directions.
    const communication = getObject(scheme, 'communication');
    const bubbleSurfaces: Array<[string, string]> = [
      ['communication.incomingSurface', getString(communication, 'incomingSurface')],
      ['communication.outgoingSurface', getString(communication, 'outgoingSurface')],
    ];
    const bubbleForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
    ];
    for (const [foregroundRole, foreground] of bubbleForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of bubbleSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Non-text: the selected/active state indicator (a solid bar, not the wash) must
    // remain perceivable against the surface it is drawn on (WCAG 1.4.11, 3:1 minimum).
    requireRatio(
      contrastRatio(getString(primary, 'main'), backgroundPaper),
      3,
      schemeName,
      'primary.main (selection cue)',
      'background.paper',
    );
  }
}

function emitTokens(resolved: JsonObject): string {
  const tier1 = getObject(resolved, 'tier1');
  const tier2 = getObject(resolved, 'tier2');
  const tier3 = getObject(resolved, 'tier3');
  return (
    header +
    'export const brandPalette = ' +
    stableStringify(getObject(tier1, 'brandPalette')) +
    ' as const;\n\n' +
    'export const brandTypography = ' +
    stableStringify(getObject(tier1, 'brandTypography')) +
    ' as const;\n\n' +
    'export const layoutTokens = ' +
    stableStringify(getObject(tier1, 'layout')) +
    ' as const;\n\n' +
    'export const effectTokens = ' +
    stableStringify(getObject(tier1, 'effects')) +
    ' as const;\n\n' +
    'export const semanticColorSchemes = ' +
    stableStringify(getObject(tier2, 'colorSchemes')) +
    ' as const;\n\n' +
    'export const typography = ' +
    stableStringify(getObject(tier2, 'typography')) +
    ' as const;\n\n' +
    'export const shape = ' +
    stableStringify(getObject(tier2, 'shape')) +
    ' as const;\n\n' +
    'export const componentTokens = ' +
    stableStringify(tier3) +
    ' as const;\n\n' +
    'export const skeletonTokens = componentTokens.skeleton;\n'
  );
}

function resolveTokens(tokensJsonSource: string): JsonObject {
  const raw = JSON.parse(tokensJsonSource) as JsonValue;
  if (!isObject(raw)) throw new Error('tokens.json must contain a JSON object');
  const resolved = resolveValue(raw, raw);
  if (!isObject(resolved)) throw new Error('Resolved token source must be an object');
  validateContrast(getObject(getObject(resolved, 'tier2'), 'colorSchemes'));
  return resolved;
}

/**
 * Deterministically resolves `tokens.json` source text into the generated module
 * source. Pure and side-effect free so it can be exercised directly by tests without
 * touching the filesystem.
 */
export function generateThemeSource(tokensJsonSource: string): string {
  return emitTokens(resolveTokens(tokensJsonSource)).replace(/\r\n/g, '\n');
}

// Mirrors MUI getContrastText for the scheme's contrastThreshold.
function contrastTextFor(background: string, threshold: number): string {
  return contrastRatio('#FFFFFF', background) >= threshold ? '#FFFFFF' : 'rgba(0, 0, 0, 0.87)';
}

function colorDeclarations(scheme: JsonObject): Array<[string, string]> {
  const text = getObject(scheme, 'text');
  const background = getObject(scheme, 'background');
  const surface = getObject(scheme, 'surface');
  const action = getObject(scheme, 'action');
  const primary = getString(getObject(scheme, 'primary'), 'main');
  const threshold = scheme.contrastThreshold;
  if (typeof threshold !== 'number') throw new Error('Expected numeric contrastThreshold');
  return [
    ['color-background', getString(background, 'default')],
    ['color-paper', getString(background, 'paper')],
    ['color-surface-subtle', getString(surface, 'subtle')],
    ['color-text', getString(text, 'primary')],
    ['color-text-secondary', getString(text, 'secondary')],
    ['color-text-muted', getString(text, 'muted')],
    ['color-text-disabled', getString(text, 'disabled')],
    ['color-primary', primary],
    ['color-on-primary', contrastTextFor(primary, threshold)],
    ['color-secondary', getString(getObject(scheme, 'secondary'), 'main')],
    ['color-success', getString(getObject(scheme, 'success'), 'main')],
    ['color-warning', getString(getObject(scheme, 'warning'), 'main')],
    ['color-error', getString(getObject(scheme, 'error'), 'main')],
    ['color-info', getString(getObject(scheme, 'info'), 'main')],
    ['color-divider', getString(scheme, 'divider')],
    ['color-hover', getString(action, 'hover')],
    ['color-selected', getString(action, 'selected')],
    ['color-disabled', getString(action, 'disabled')],
    ['shadow-raised', getString(surface, 'elevation')],
    ['shadow-overlay', getString(surface, 'overlay')],
    ['rim', getString(surface, 'rim')],
    ['glow', getString(surface, 'glow')],
  ];
}

function declarationBlock(selector: string, declarations: Array<[string, string]>, indent: string): string {
  const lines = declarations.map(([name, value]) => indent + '  --dipsy-' + name + ': ' + value + ';');
  return indent + selector + ' {\n' + lines.join('\n') + '\n' + indent + '}';
}

/**
 * Emits the CSS custom properties consumed by surfaces that cannot import the React
 * theme (extension popup, desktop provisioning page).
 */
export function generateStaticTokensCss(tokensJsonSource: string): string {
  const resolved = resolveTokens(tokensJsonSource);
  const tier1 = getObject(resolved, 'tier1');
  const typography = getObject(tier1, 'brandTypography');
  const weights = getObject(typography, 'weights');
  const layout = getObject(tier1, 'layout');
  const radius = getObject(layout, 'radius');
  const effects = getObject(tier1, 'effects');
  const focus = getObject(effects, 'focus');
  const motion = getObject(effects, 'motion');
  const duration = getObject(motion, 'duration');
  const easing = getObject(motion, 'easing');
  const colorSchemes = getObject(getObject(resolved, 'tier2'), 'colorSchemes');
  const px = (value: JsonValue): string => String(value) + 'px';

  const shared: Array<[string, string]> = [
    ['font-family', getString(typography, 'fontFamily')],
    ['font-family-mono', getString(typography, 'fontFamilyMono')],
    ...['regular', 'medium', 'semibold', 'bold'].map(
      (weight): [string, string] => ['font-weight-' + weight, String(weights[weight])],
    ),
    ...['compact', 'control', 'message', 'surface', 'pill'].map(
      (size): [string, string] => ['radius-' + size, px(radius[size])],
    ),
    ['space-unit', px(layout.spacingUnit)],
    ['border-thin', getString(getObject(effects, 'borders'), 'thin')],
    ['focus-width', getString(focus, 'width')],
    ['focus-offset', getString(focus, 'offset')],
    ...['fast', 'standard', 'spatial'].map(
      (speed): [string, string] => ['motion-' + speed, getString(duration, speed)],
    ),
    ...['standard', 'enter', 'exit'].map(
      (curve): [string, string] => ['easing-' + curve, getString(easing, curve)],
    ),
    ['press-scale', String(motion.pressScale)],
  ];
  return (
    '/* Generated from frontend/src/theme/tokens.json; run npm run sync:static-tokens in frontend. */\n' +
    declarationBlock(':root', [...shared, ...colorDeclarations(getObject(colorSchemes, 'light'))], '') +
    '\n@media (prefers-color-scheme: dark) {\n' +
    declarationBlock(':root', colorDeclarations(getObject(colorSchemes, 'dark')), '  ') +
    '\n}\n'
  ).replace(/\r\n/g, '\n');
}

const STATIC_BLOCK_START = '/* design-tokens:start */';
const STATIC_BLOCK_END = '/* design-tokens:end */';

/** Replaces the marker-delimited token block, keeping the start marker's indentation. */
export function replaceStaticTokenBlock(consumerSource: string, css: string): string {
  const source = consumerSource.replace(/\r\n/g, '\n');
  const start = source.indexOf(STATIC_BLOCK_START);
  const end = source.indexOf(STATIC_BLOCK_END);
  if (start < 0 || end < start || source.indexOf(STATIC_BLOCK_START, start + 1) >= 0) {
    throw new Error('Expected exactly one ordered design-tokens marker pair');
  }
  const lineStart = source.lastIndexOf('\n', start) + 1;
  const indent = source.slice(lineStart, start);
  if (!/^[ \t]*$/.test(indent)) throw new Error('design-tokens:start must begin its line');
  const body = css
    .trimEnd()
    .split('\n')
    .map((line) => (line.length === 0 ? line : indent + line))
    .join('\n');
  return source.slice(0, start) + STATIC_BLOCK_START + '\n' + body + '\n' + indent + source.slice(end);
}

export const staticTokenConsumers = ['extension/popup.css', 'app/provisioning/provisioning.html'];
const repositoryRoot = path.resolve(themeDirectory, '..', '..', '..');

function writeIfChanged(filePath: string, content: string): boolean {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function main(): void {
  const tokensSource = fs.readFileSync(sourcePath, 'utf8');
  fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeIfChanged(generatedPath, generateThemeSource(tokensSource));
  const css = generateStaticTokensCss(tokensSource);
  writeIfChanged(staticTokensPath, css);
  console.log('Theme generated deterministically from tokens.json');
  if (process.argv.includes('--static-surfaces')) {
    for (const consumer of staticTokenConsumers) {
      const consumerPath = path.join(repositoryRoot, consumer);
      const updated = replaceStaticTokenBlock(fs.readFileSync(consumerPath, 'utf8'), css);
      if (writeIfChanged(consumerPath, updated)) console.log('Updated design tokens in ' + consumer);
    }
  }
}

const isMainModule = process.argv[1] !== undefined
  && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMainModule) main();
