import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

type RgbColor = {
  r: number;
  g: number;
  b: number;
  a: number;
  inSrgb: boolean;
};

const filename = fileURLToPath(import.meta.url);
const themeDirectory = path.dirname(filename);
const sourcePath = path.join(themeDirectory, 'tokens.json');
const generatedPath = path.join(themeDirectory, 'generated', 'tokens.ts');
const staticTokensPath = path.join(themeDirectory, 'generated', 'static-tokens.css');
const header =
  '// AUTO-GENERATED FROM src/theme/tokens.json.\n// DO NOT EDIT THIS FILE DIRECTLY.\n\n';

const WHITE = 'oklch(100% 0 0)';
const BLACK_87 = 'oklch(0% 0 0 / 0.87)';
const SRGB_EPSILON = 5e-4;

function isObject(value: JsonValue | undefined): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function readPath(root: JsonObject, tokenPath: string): JsonValue {
  let value: JsonValue = root;
  for (const segment of tokenPath.split('.')) {
    if (!isObject(value) || !(segment in value)) {
      throw new Error('Unknown token reference: {' + tokenPath + '}');
    }
    value = value[segment];
  }
  return value;
}

function resolveValue(value: JsonValue, root: JsonObject, stack: string[] = []): JsonValue {
  if (typeof value === 'string') {
    const reference = /^\{([^}]+)\}$/.exec(value);
    if (!reference) return value;
    const tokenPath = reference[1];
    if (stack.includes(tokenPath)) {
      throw new Error('Circular token reference: ' + [...stack, tokenPath].join(' -> '));
    }
    return resolveValue(readPath(root, tokenPath), root, [...stack, tokenPath]);
  }
  if (Array.isArray(value)) return value.map((entry) => resolveValue(entry, root, stack));
  if (!isObject(value)) return value;

  return Object.fromEntries(
    Object.keys(value)
      .filter((key) => !key.startsWith('_'))
      .sort()
      .map((key) => [key, resolveValue(value[key], root, stack)]),
  );
}

function stableStringify(value: JsonValue): string {
  const normalize = (entry: JsonValue): JsonValue => {
    if (Array.isArray(entry)) return entry.map(normalize);
    if (!isObject(entry)) return entry;
    return Object.fromEntries(
      Object.keys(entry)
        .sort()
        .map((key) => [key, normalize(entry[key])]),
    );
  };
  return JSON.stringify(normalize(value), null, 2);
}

function getObject(parent: JsonObject, key: string): JsonObject {
  const value = parent[key];
  if (!isObject(value)) throw new Error('Expected token object at ' + key);
  return value;
}

function getString(parent: JsonObject, key: string): string {
  const value = parent[key];
  if (typeof value !== 'string') throw new Error('Expected string token at ' + key);
  return value;
}

function linearToSrgb(channel: number): number {
  return channel <= 0.0031308
    ? channel * 12.92
    : 1.055 * channel ** (1 / 2.4) - 0.055;
}

function oklchToRgb(lightness: number, chroma: number, hue: number, alpha: number): RgbColor {
  const radians = (hue * Math.PI) / 180;
  const a = chroma * Math.cos(radians);
  const b = chroma * Math.sin(radians);
  const lPrime = lightness + 0.3963377774 * a + 0.2158037573 * b;
  const mPrime = lightness - 0.1055613458 * a - 0.0638541728 * b;
  const sPrime = lightness - 0.0894841775 * a - 1.291485548 * b;

  const l = lPrime ** 3;
  const m = mPrime ** 3;
  const s = sPrime ** 3;

  const linearR = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  const linearG = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  const linearB = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  const inSrgb = [linearR, linearG, linearB].every(
    (channel) => channel >= -SRGB_EPSILON && channel <= 1 + SRGB_EPSILON,
  );

  return {
    r: Math.min(1, Math.max(0, linearToSrgb(linearR))),
    g: Math.min(1, Math.max(0, linearToSrgb(linearG))),
    b: Math.min(1, Math.max(0, linearToSrgb(linearB))),
    a: alpha,
    inSrgb,
  };
}

function parseColor(value: string): RgbColor {
  const oklchMatch = /^oklch\(\s*([+-]?[\d.]+%?)\s+([+-]?[\d.]+)\s+([+-]?[\d.]+)(?:deg)?(?:\s*\/\s*([+-]?[\d.]+%?))?\s*\)$/i.exec(value);
  if (oklchMatch) {
    const lightnessRaw = oklchMatch[1];
    const lightness = lightnessRaw.endsWith('%')
      ? Number.parseFloat(lightnessRaw) / 100
      : Number.parseFloat(lightnessRaw);
    const chroma = Number.parseFloat(oklchMatch[2]);
    const hue = ((Number.parseFloat(oklchMatch[3]) % 360) + 360) % 360;
    const alphaRaw = oklchMatch[4];
    const alpha = alphaRaw === undefined
      ? 1
      : alphaRaw.endsWith('%')
        ? Number.parseFloat(alphaRaw) / 100
        : Number.parseFloat(alphaRaw);
    if (![lightness, chroma, hue, alpha].every(Number.isFinite)) {
      throw new Error('Invalid OKLCH color: ' + value);
    }
    if (lightness < 0 || lightness > 1 || chroma < 0 || alpha < 0 || alpha > 1) {
      throw new Error('OKLCH color component out of range: ' + value);
    }
    return oklchToRgb(lightness, chroma, hue, alpha);
  }
  throw new Error('Color validation requires an OKLCH color, received ' + value);
}

function validateCanonicalColorSyntax(tokensJsonSource: string): void {
  if (/(#[0-9a-f]{3,8}\b|rgba?\()/i.test(tokensJsonSource)) {
    throw new Error('Design color tokens must use OKLCH; legacy hex/rgb syntax is not allowed');
  }
  if (/color\(\s*display-p3/i.test(tokensJsonSource)) {
    throw new Error('Design color tokens must use OKLCH rather than Display-P3 coordinates');
  }
}

function validateSrgbGamut(tokensJsonSource: string): void {
  const colors = Array.from(tokensJsonSource.matchAll(/oklch\([^)]*\)/gi), (match) => match[0]);
  for (const color of colors) {
    if (!parseColor(color).inSrgb) {
      throw new Error('Core design color is outside the guaranteed sRGB gamut: ' + color);
    }
  }
}

// Composites a possibly-translucent color over an opaque backdrop before measuring.
function flattenOverBackground(value: string, backdrop: string | RgbColor): RgbColor {
  const color = parseColor(value);
  const resolvedBackdrop = typeof backdrop === 'string' ? parseColor(backdrop) : backdrop;
  if (resolvedBackdrop.a < 1) throw new Error('Contrast backdrop must be opaque');
  if (color.a >= 1) return { ...color, a: 1 };
  return {
    r: color.a * color.r + (1 - color.a) * resolvedBackdrop.r,
    g: color.a * color.g + (1 - color.a) * resolvedBackdrop.g,
    b: color.a * color.b + (1 - color.a) * resolvedBackdrop.b,
    a: 1,
    inSrgb: color.inSrgb && resolvedBackdrop.inSrgb,
  };
}

function toLinear(channel: number): number {
  return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
}

function relativeLuminance({ r, g, b }: Pick<RgbColor, 'r' | 'g' | 'b'>): number {
  const [red, green, blue] = [r, g, b].map(toLinear);
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
}

function contrastRatio(foreground: string, backdrop: string): number {
  const backdropColor = parseColor(backdrop);
  if (backdropColor.a < 1) throw new Error('Contrast backdrop must be opaque');
  const flattened = flattenOverBackground(foreground, backdropColor);
  const foregroundLuminance = relativeLuminance(flattened);
  const backdropLuminance = relativeLuminance(backdropColor);
  const light = Math.max(foregroundLuminance, backdropLuminance);
  const dark = Math.min(foregroundLuminance, backdropLuminance);
  return (light + 0.05) / (dark + 0.05);
}

function contrastRatioOnComposite(foreground: string, overlay: string, backdrop: string): number {
  const composite = flattenOverBackground(overlay, backdrop);
  const flattenedForeground = flattenOverBackground(foreground, composite);
  const foregroundLuminance = relativeLuminance(flattenedForeground);
  const compositeLuminance = relativeLuminance(composite);
  const light = Math.max(foregroundLuminance, compositeLuminance);
  const dark = Math.min(foregroundLuminance, compositeLuminance);
  return (light + 0.05) / (dark + 0.05);
}

function requireRatio(ratio: number, minimum: number, schemeName: string, foregroundRole: string, surfaceRole: string): void {
  if (ratio < minimum) {
    throw new Error(
      schemeName +
        '.' +
        foregroundRole +
        ' on ' +
        surfaceRole +
        ' has ' +
        ratio.toFixed(2) +
        ':1 contrast, below the ' +
        minimum +
        ':1 minimum',
    );
  }
}

const INTENTS = ['primary', 'secondary', 'accent', 'calm', 'success', 'warning', 'error', 'info'];

// Picks the higher-contrast of white and 87% black that meets the scheme's contrastThreshold.
function contrastTextFor(background: string, threshold: number): string {
  const candidates = [WHITE, BLACK_87]
    .map((color) => ({ color, ratio: contrastRatio(color, background) }))
    .sort((left, right) => right.ratio - left.ratio);
  const passing = candidates.find((candidate) => candidate.ratio >= threshold);
  if (passing) return passing.color;
  throw new Error(
    'No supported on-color reaches ' + threshold + ':1 contrast on ' + background,
  );
}

// Native CSS color derives tonal variants but decides text colour by lightness alone,
// so each intent carries its WCAG-derived text colour.
function addContrastText(colorSchemes: JsonObject): void {
  for (const schemeName of ['light', 'dark']) {
    const scheme = getObject(colorSchemes, schemeName);
    const threshold = scheme.contrastThreshold;
    if (typeof threshold !== 'number') throw new Error('Expected numeric contrastThreshold');
    for (const intent of INTENTS) {
      const color = getObject(scheme, intent);
      if (!('contrastText' in color)) {
        color.contrastText = contrastTextFor(getString(color, 'main'), threshold);
      }
    }
  }
}

function validateContrast(colorSchemes: JsonObject): void {
  for (const schemeName of ['light', 'dark']) {
    const scheme = getObject(colorSchemes, schemeName);
    const text = getObject(scheme, 'text');
    const background = getObject(scheme, 'background');
    const surface = getObject(scheme, 'surface');
    const primary = getObject(scheme, 'primary');

    const backgroundDefault = getString(background, 'default');
    const backgroundPaper = getString(background, 'paper');
    const surfaceSubtle = getString(surface, 'subtle');
    const surfaceGlass = getString(surface, 'glass');

    const textSurfaces: Array<[string, string]> = [
      ['background.default', backgroundDefault],
      ['background.paper', backgroundPaper],
      ['surface.subtle', surfaceSubtle],
    ];
    const textForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
      ...(('muted' in text ? [['text.muted', getString(text, 'muted')]] : []) as Array<
        [string, string]
      >),
    ];
    for (const [foregroundRole, foreground] of textForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of textSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
      // The AppBar renders its translucent glass surface over ambient page content;
      // background.default is used as the representative backdrop for that composite.
      requireRatio(
        contrastRatioOnComposite(foreground, surfaceGlass, backgroundDefault),
        4.5,
        schemeName,
        foregroundRole,
        'surface.glass (AppBar composite)',
      );
    }

    // Feedback foregrounds are checked against background.default and background.paper.
    const feedbackForegroundRoles: Array<[string, string]> = [
      ['success.main', getString(getObject(scheme, 'success'), 'main')],
      ['warning.main', getString(getObject(scheme, 'warning'), 'main')],
      ['error.main', getString(getObject(scheme, 'error'), 'main')],
    ];
    for (const [foregroundRole, foreground] of feedbackForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of [
        ['background.default', backgroundDefault],
        ['background.paper', backgroundPaper],
      ] as Array<[string, string]>) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Message bubbles render body text (text.primary) and metadata (text.secondary)
    // on their own opaque surfaces; links inherit the body color, so no separate link
    // role is measured.
    const communication = getObject(scheme, 'communication');
    const bubbleSurfaces: Array<[string, string]> = [
      ['communication.incomingSurface', getString(communication, 'incomingSurface')],
      ['communication.outgoingSurface', getString(communication, 'outgoingSurface')],
    ];
    const bubbleForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
    ];
    for (const [foregroundRole, foreground] of bubbleForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of bubbleSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Non-text: the selected/active state indicator (a solid bar, not the wash) must
    // remain perceivable against the surface it is drawn on (WCAG 1.4.11, 3:1 minimum).
    requireRatio(
      contrastRatio(getString(primary, 'main'), backgroundPaper),
      3,
      schemeName,
      'primary.main (selection cue)',
      'background.paper',
    );

    for (const intent of INTENTS) {
      const intentColor = getObject(scheme, intent);
      requireRatio(
        contrastRatio(getString(intentColor, 'contrastText'), getString(intentColor, 'main')),
        4.5,
        schemeName,
        intent + '.contrastText',
        intent + '.main',
      );
    }
  }
}

function emitTokens(resolved: JsonObject): string {
  const tier1 = getObject(resolved, 'tier1');
  const tier2 = getObject(resolved, 'tier2');
  const tier3 = getObject(resolved, 'tier3');
  return (
    header +
    'export const brandPalette = ' +
    stableStringify(getObject(tier1, 'brandPalette')) +
    ' as const;\n\n' +
    'export const brandTypography = ' +
    stableStringify(getObject(tier1, 'brandTypography')) +
    ' as const;\n\n' +
    'export const layoutTokens = ' +
    stableStringify(getObject(tier1, 'layout')) +
    ' as const;\n\n' +
    'export const effectTokens = ' +
    stableStringify(getObject(tier1, 'effects')) +
    ' as const;\n\n' +
    'export const semanticColorSchemes = ' +
    stableStringify(getObject(tier2, 'colorSchemes')) +
    ' as const;\n\n' +
    'export const typography = ' +
    stableStringify(getObject(tier2, 'typography')) +
   ' as const;\n\n' +
    'export const shape = ' +
    stableStringify(getObject(tier2, 'shape')) +
    ' as const;\n\n' +
    'export const componentTokens = ' +
    stableStringify(tier3) +
    ' as const;\n\n' +
    'export const skeletonTokens = componentTokens.skeleton;\n'
  );
}

function resolveTokens(tokensJsonSource: string): JsonObject {
  validateCanonicalColorSyntax(tokensJsonSource);
  validateSrgbGamut(tokensJsonSource);
  const raw = JSON.parse(tokensJsonSource) as JsonValue;
  if (!isObject(raw)) throw new Error('tokens.json must contain a JSON object');
  const resolved = resolveValue(raw, raw);
  if (!isObject(resolved)) throw new Error('Resolved token source must be an object');
  const colorSchemes = getObject(getObject(resolved, 'tier2'), 'colorSchemes');
  addContrastText(colorSchemes);
  validateContrast(colorSchemes);
  return resolved;
}

/**
 * Deterministically resolves `tokens.json` source text into the generated module
 * source. Pure and side-effect free so it can be exercised directly by tests without
 * touching the filesystem.
 */
export function generateThemeSource(tokensJsonSource: string): string {
  return emitTokens(resolveTokens(tokensJsonSource)).replace(/\r\n/g, '\n');
}

function colorDeclarations(scheme: JsonObject): Array<[string, string]> {
  const text = getObject(scheme, 'text');
  const background = getObject(scheme, 'background');
  const surface = getObject(scheme, 'surface');
  const action = getObject(scheme, 'action');
  const primary = getObject(scheme, 'primary');
  const declarations: Array<[string, string]> = [
    ['color-background', getString(background, 'default')],
    ['color-paper', getString(background, 'paper')],
    ['color-surface-subtle', getString(surface, 'subtle')],
    ['color-text', getString(text, 'primary')],
    ['color-text-secondary', getString(text, 'secondary')],
    ['color-text-muted', getString(text, 'muted')],
    ['color-text-disabled', getString(text, 'disabled')],
    ['color-primary', getString(primary, 'main')],
    ['color-on-primary', getString(primary, 'contrastText')],
    ['color-secondary', getString(getObject(scheme, 'secondary'), 'main')],
    ['color-success', getString(getObject(scheme, 'success'), 'main')],
    ['color-warning', getString(getObject(scheme, 'warning'), 'main')],
    ['color-error', getString(getObject(scheme, 'error'), 'main')],
    ['color-info', getString(getObject(scheme, 'info'), 'main')],
    ['color-divider', getString(scheme, 'divider')],
    ['color-hover', getString(action, 'hover')],
    ['color-selected', getString(action, 'selected')],
    ['color-disabled', getString(action, 'disabled')],
    ['shadow-raised', getString(surface, 'elevation')],
    ['shadow-overlay', getString(surface, 'overlay')],
    ['rim', getString(surface, 'rim')],
    ['glow', getString(surface, 'glow')],
  ];
  return declarations;
}

function declarationBlock(selector: string, declarations: Array<[string, string]>, indent: string): string {
  const lines = declarations.map(([name, value]) => indent + '  --dipsy-' + name + ': ' + value + ';');
  return indent + selector + ' {\n' + lines.join('\n') + '\n' + indent + '}';
}

/**
 * Emits the CSS custom properties consumed by surfaces that cannot import the React
 * theme (extension popup, desktop provisioning page).
 */
export function generateStaticTokensCss(tokensJsonSource: string): string {
  const resolved = resolveTokens(tokensJsonSource);
  const tier1 = getObject(resolved, 'tier1');
  const typography = getObject(tier1, 'brandTypography');
  const weights = getObject(typography, 'weights');
  const layout = getObject(tier1, 'layout');
  const radius = getObject(layout, 'radius');
  const effects = getObject(tier1, 'effects');
  const focus = getObject(effects, 'focus');
  const motion = getObject(effects, 'motion');
  const duration = getObject(motion, 'duration');
  const easing = getObject(motion, 'easing');
  const colorSchemes = getObject(getObject(resolved, 'tier2'), 'colorSchemes');
  const px = (value: JsonValue): string => String(value) + 'px';

  const shared: Array<[string, string]> = [
    ['font-family', getString(typography, 'fontFamily')],
    ['font-family-mono', getString(typography, 'fontFamilyMono')],
    ...['regular', 'medium', 'semibold', 'bold'].map(
      (weight): [string, string] => ['font-weight-' + weight, String(weights[weight])],
    ),
    ...['compact', 'control', 'message', 'surface', 'pill'].map(
      (size): [string, string] => ['radius-' + size, px(radius[size])],
    ),
    ['space-unit', px(layout.spacingUnit)],
    ['border-thin', getString(getObject(effects, 'borders'), 'thin')],
    ['focus-width', getString(focus, 'width')],
    ['focus-offset', getString(focus, 'offset')],
    ...['fast', 'standard', 'spatial'].map(
      (speed): [string, string] => ['motion-' + speed, getString(duration, speed)],
    ),
    ...['standard', 'enter', 'exit'].map(
      (curve): [string, string] => ['easing-' + curve, getString(easing, curve)],
    ),
    ['press-scale', String(motion.pressScale)],
  ];
  return (
    '/* Generated from frontend/src/theme/tokens.json; run npm run sync:static-tokens in frontend. */\n' +
    declarationBlock(':root', [...shared, ...colorDeclarations(getObject(colorSchemes, 'light'))], '') +
    '\n@media (prefers-color-scheme: dark) {\n' +
    declarationBlock(':root', colorDeclarations(getObject(colorSchemes, 'dark')), '  ') +
    '\n}\n'
  ).replace(/\r\n/g, '\n');
}

const STATIC_BLOCK_START = '/* design-tokens:start */';
const STATIC_BLOCK_END = '/* design-tokens:end */';

/** Replaces the marker-delimited token block, keeping the start marker's indentation. */
export function replaceStaticTokenBlock(consumerSource: string, css: string): string {
  const source = consumerSource.replace(/\r\n/g, '\n');
  const start = source.indexOf(STATIC_BLOCK_START);
  const end = source.indexOf(STATIC_BLOCK_END);
  if (start < 0 || end < start || source.indexOf(STATIC_BLOCK_START, start + 1) >= 0) {
    throw new Error('Expected exactly one ordered design-tokens marker pair');
  }
  const lineStart = source.lastIndexOf('\n', start) + 1;
  const indent = source.slice(lineStart, start);
  if (!/^[ \t]*$/.test(indent)) throw new Error('design-tokens:start must begin its line');
  const body = css
    .trimEnd()
    .split('\n')
    .map((line) => (line.length === 0 ? line : indent + line))
    .join('\n');
  return source.slice(0, start) + STATIC_BLOCK_START + '\n' + body + '\n' + indent + source.slice(end);
}

export const staticTokenConsumers = ['extension/popup.css', 'app/provisioning/provisioning.html'];
const repositoryRoot = path.resolve(themeDirectory, '..', '..', '..');

function writeIfChanged(filePath: string, content: string): boolean {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function main(): void {
  const tokensSource = fs.readFileSync(sourcePath, 'utf8');
  fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeIfChanged(generatedPath, generateThemeSource(tokensSource));
  const css = generateStaticTokensCss(tokensSource);
  writeIfChanged(staticTokensPath, css);
  console.log('Theme generated deterministically from tokens.json');
  if (process.argv.includes('--static-surfaces')) {
    for (const consumer of staticTokenConsumers) {
      const consumerPath = path.join(repositoryRoot, consumer);
      const updated = replaceStaticTokenBlock(fs.readFileSync(consumerPath, 'utf8'), css);
      if (writeIfChanged(consumerPath, updated)) console.log('Updated design tokens in ' + consumer);
    }
  }
}

const isMainModule = process.argv[1] !== undefined
  && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMainModule) main();
