import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { qualifyThemeColors } from './chart-qualification.ts';
import { contrastRatio, contrastRatioOnComposite } from './color-validation.ts';
import { buildTokenGraph, isObject, publicIntents, validateBridgeIntents, type JsonObject, type JsonValue } from './intent-contracts.ts';
import { validateRepositoryConsumers } from './token-consumers.ts';

const filename = fileURLToPath(import.meta.url);
const themeDirectory = path.dirname(filename);
const sourcePath = path.join(themeDirectory, 'tokens.json');
const generatedPath = path.join(themeDirectory, 'generated', 'tokens.ts');
const staticTokensPath = path.join(themeDirectory, 'generated', 'static-tokens.css');
const header =
  '// AUTO-GENERATED FROM src/theme/tokens.json.\n// DO NOT EDIT THIS FILE DIRECTLY.\n\n';

function stableStringify(value: JsonValue): string {
  const normalize = (entry: JsonValue): JsonValue => {
    if (Array.isArray(entry)) return entry.map(normalize);
    if (!isObject(entry)) return entry;
    return Object.fromEntries(
      Object.keys(entry)
        .sort()
        .map((key) => [key, normalize(entry[key])]),
    );
  };
  return JSON.stringify(normalize(value), null, 2);
}

function getObject(parent: JsonObject, key: string): JsonObject {
  const value = parent[key];
  if (!isObject(value)) throw new Error('Expected token object at ' + key);
  return value;
}

function getString(parent: JsonObject, key: string): string {
  const value = parent[key];
  if (typeof value !== 'string') throw new Error('Expected string token at ' + key);
  return value;
}

function requireRatio(ratio: number, minimum: number, schemeName: string, foregroundRole: string, surfaceRole: string): void {
  if (ratio < minimum) {
    throw new Error(
      schemeName +
        '.' +
        foregroundRole +
        ' on ' +
        surfaceRole +
        ' has ' +
        ratio.toFixed(2) +
        ':1 contrast, below the ' +
        minimum +
        ':1 minimum',
    );
  }
}

const INTENTS = ['primary', 'secondary', 'accent', 'calm', 'success', 'warning', 'error', 'info'];

function validateContrast(colorSchemes: JsonObject): void {
  for (const schemeName of ['light', 'dark']) {
    const scheme = getObject(colorSchemes, schemeName);
    const text = getObject(scheme, 'text');
    const background = getObject(scheme, 'background');
    const surface = getObject(scheme, 'surface');
    const primary = getObject(scheme, 'primary');

    const backgroundDefault = getString(background, 'default');
    const backgroundPaper = getString(background, 'paper');
    const surfaceSubtle = getString(surface, 'subtle');
    const surfaceGlass = getString(surface, 'glass');

    const textSurfaces: Array<[string, string]> = [
      ['background.default', backgroundDefault],
      ['background.paper', backgroundPaper],
      ['surface.subtle', surfaceSubtle],
    ];
    const textForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
      ...(('muted' in text ? [['text.muted', getString(text, 'muted')]] : []) as Array<
        [string, string]
      >),
    ];
    for (const [foregroundRole, foreground] of textForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of textSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
      // The AppBar renders its translucent glass surface over ambient page content;
      // background.default is used as the representative backdrop for that composite.
      requireRatio(
        contrastRatioOnComposite(foreground, surfaceGlass, backgroundDefault),
        4.5,
        schemeName,
        foregroundRole,
        'surface.glass (AppBar composite)',
      );
    }

    // Feedback foregrounds are checked against background.default and background.paper.
    const feedbackForegroundRoles: Array<[string, string]> = [
      ['success.main', getString(getObject(scheme, 'success'), 'main')],
      ['warning.main', getString(getObject(scheme, 'warning'), 'main')],
      ['error.main', getString(getObject(scheme, 'error'), 'main')],
    ];
    for (const [foregroundRole, foreground] of feedbackForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of [
        ['background.default', backgroundDefault],
        ['background.paper', backgroundPaper],
      ] as Array<[string, string]>) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Message bubbles render body text (text.primary) and metadata (text.secondary)
    // on their own opaque surfaces; links inherit the body color, so no separate link
    // role is measured.
    const communication = getObject(scheme, 'communication');
    const bubbleSurfaces: Array<[string, string]> = [
      ['communication.incomingSurface', getString(communication, 'incomingSurface')],
      ['communication.outgoingSurface', getString(communication, 'outgoingSurface')],
    ];
    const bubbleForegroundRoles: Array<[string, string]> = [
      ['text.primary', getString(text, 'primary')],
      ['text.secondary', getString(text, 'secondary')],
    ];
    for (const [foregroundRole, foreground] of bubbleForegroundRoles) {
      for (const [surfaceRole, surfaceColor] of bubbleSurfaces) {
        requireRatio(
          contrastRatio(foreground, surfaceColor),
          4.5,
          schemeName,
          foregroundRole,
          surfaceRole,
        );
      }
    }

    // Non-text: the selected/active state indicator (a solid bar, not the wash) must
    // remain perceivable against the surface it is drawn on (WCAG 1.4.11, 3:1 minimum).
    requireRatio(
      contrastRatio(getString(primary, 'main'), backgroundPaper),
      3,
      schemeName,
      'primary.main (selection cue)',
      'background.paper',
    );

    for (const intent of INTENTS) {
      const intentColor = getObject(scheme, intent);
      requireRatio(
        contrastRatio(getString(intentColor, 'contrastText'), getString(intentColor, 'main')),
        4.5,
        schemeName,
        intent + '.contrastText',
        intent + '.main',
      );
    }
  }
}

function emitTokens(resolved: JsonObject): string {
  const tier1 = getObject(resolved, 'tier1');
  const tier2 = getObject(resolved, 'tier2');
  const tier3 = getObject(resolved, 'tier3');
  return (
    header +
    'export const brandPalette = ' +
    stableStringify(getObject(tier1, 'brandPalette')) +
    ' as const;\n\n' +
    'export const brandTypography = ' +
    stableStringify(getObject(tier1, 'brandTypography')) +
    ' as const;\n\n' +
    'export const layoutTokens = ' +
    stableStringify(getObject(tier1, 'layout')) +
    ' as const;\n\n' +
    'export const effectTokens = ' +
    stableStringify(getObject(tier1, 'effects')) +
    ' as const;\n\n' +
    'export const semanticIntents = ' +
    stableStringify(getObject(tier2, 'intents')) +
    ' as const;\n\n' +
    'export const semanticColorSchemes = ' +
    stableStringify(getObject(tier2, 'colorSchemes')) +
    ' as const;\n\n' +
    'export const typography = ' +
    stableStringify(getObject(tier2, 'typography')) +
   ' as const;\n\n' +
    'export const shape = ' +
    stableStringify(getObject(tier2, 'shape')) +
    ' as const;\n\n' +
    'export const componentTokens = ' +
    stableStringify(tier3) +
    ' as const;\n\n' +
    'export const skeletonTokens = componentTokens.skeleton;\n'
  );
}

function resolveTokens(tokensJsonSource: string): JsonObject {
  const raw = JSON.parse(tokensJsonSource) as JsonValue;
  if (!isObject(raw)) throw new Error('tokens.json must contain a JSON object');
  const graph = buildTokenGraph(raw);
  validateBridgeIntents(graph);
  const resolved = graph.resolved;
  const tier2 = getObject(resolved, 'tier2');
  tier2.intents = publicIntents(graph);
  validateContrast(getObject(tier2, 'colorSchemes'));
  qualifyThemeColors(resolved);
  return resolved;
}

/**
 * Deterministically resolves `tokens.json` source text into the generated module
 * source. Pure and side-effect free so it can be exercised directly by tests without
 * touching the filesystem.
 */
export function generateThemeSource(tokensJsonSource: string): string {
  return emitTokens(resolveTokens(tokensJsonSource)).replace(/\r\n/g, '\n');
}

function colorDeclarations(scheme: JsonObject): Array<[string, string]> {
  const text = getObject(scheme, 'text');
  const background = getObject(scheme, 'background');
  const surface = getObject(scheme, 'surface');
  const action = getObject(scheme, 'action');
  const primary = getObject(scheme, 'primary');
  const declarations: Array<[string, string]> = [
    ['color-background', getString(background, 'default')],
    ['color-paper', getString(background, 'paper')],
    ['color-surface-subtle', getString(surface, 'subtle')],
    ['color-text', getString(text, 'primary')],
    ['color-text-secondary', getString(text, 'secondary')],
    ['color-text-muted', getString(text, 'muted')],
    ['color-text-disabled', getString(text, 'disabled')],
    ['color-primary', getString(primary, 'main')],
    ['color-on-primary', getString(primary, 'contrastText')],
    ['color-secondary', getString(getObject(scheme, 'secondary'), 'main')],
    ['color-success', getString(getObject(scheme, 'success'), 'main')],
    ['color-warning', getString(getObject(scheme, 'warning'), 'main')],
    ['color-error', getString(getObject(scheme, 'error'), 'main')],
    ['color-info', getString(getObject(scheme, 'info'), 'main')],
    ['color-divider', getString(scheme, 'divider')],
    ['color-hover', getString(action, 'hover')],
    ['color-selected', getString(action, 'selected')],
    ['color-disabled', getString(action, 'disabled')],
    ['shadow-raised', getString(surface, 'elevation')],
    ['shadow-overlay', getString(surface, 'overlay')],
    ['rim', getString(surface, 'rim')],
    ['glow', getString(surface, 'glow')],
  ];
  return declarations;
}

function intentDeclarations(intents: JsonObject, prefix = 'intent'): Array<[string, string]> {
  return Object.entries(intents).filter(([key]) => key !== 'legacy').flatMap(([key, value]) => {
    const name = prefix + '-' + key.replace(/[A-Z]/g, (letter) => '-' + letter.toLowerCase());
    if (isObject(value)) return intentDeclarations(value, name);
    if (typeof value !== 'string') throw new Error('Expected public intent color at ' + name);
    return [[name, value] as [string, string]];
  });
}

function declarationBlock(selector: string, declarations: Array<[string, string]>, indent: string): string {
  const lines = declarations.map(([name, value]) => indent + '  --dipsy-' + name + ': ' + value + ';');
  return indent + selector + ' {\n' + lines.join('\n') + '\n' + indent + '}';
}

/**
 * Emits the CSS custom properties consumed by surfaces that cannot import the React
 * theme (extension popup, desktop provisioning page).
 */
export function generateStaticTokensCss(tokensJsonSource: string): string {
  const resolved = resolveTokens(tokensJsonSource);
  const tier1 = getObject(resolved, 'tier1');
  const typography = getObject(tier1, 'brandTypography');
  const weights = getObject(typography, 'weights');
  const layout = getObject(tier1, 'layout');
  const radius = getObject(layout, 'radius');
  const effects = getObject(tier1, 'effects');
  const focus = getObject(effects, 'focus');
  const motion = getObject(effects, 'motion');
  const duration = getObject(motion, 'duration');
  const easing = getObject(motion, 'easing');
  const colorSchemes = getObject(getObject(resolved, 'tier2'), 'colorSchemes');
  const intents = getObject(getObject(resolved, 'tier2'), 'intents');
  const px = (value: JsonValue): string => String(value) + 'px';

  const shared: Array<[string, string]> = [
    ['font-family', getString(typography, 'fontFamily')],
    ['font-family-mono', getString(typography, 'fontFamilyMono')],
    ...['regular', 'medium', 'semibold', 'bold'].map(
      (weight): [string, string] => ['font-weight-' + weight, String(weights[weight])],
    ),
    ...['compact', 'control', 'message', 'surface', 'pill'].map(
      (size): [string, string] => ['radius-' + size, px(radius[size])],
    ),
    ['space-unit', px(layout.spacingUnit)],
    ['border-thin', getString(getObject(effects, 'borders'), 'thin')],
    ['focus-width', getString(focus, 'width')],
    ['focus-offset', getString(focus, 'offset')],
    ...['fast', 'standard', 'spatial'].map(
      (speed): [string, string] => ['motion-' + speed, getString(duration, speed)],
    ),
    ...['standard', 'enter', 'exit'].map(
      (curve): [string, string] => ['easing-' + curve, getString(easing, curve)],
    ),
    ['press-scale', String(motion.pressScale)],
  ];
  return (
    '/* Generated from frontend/src/theme/tokens.json; run npm run sync:static-tokens in frontend. */\n' +
    declarationBlock(':root', [...shared, ...colorDeclarations(getObject(colorSchemes, 'light')), ...intentDeclarations(getObject(intents, 'light'))], '') +
    '\n@media (prefers-color-scheme: dark) {\n' +
    declarationBlock(':root', [...colorDeclarations(getObject(colorSchemes, 'dark')), ...intentDeclarations(getObject(intents, 'dark'))], '  ') +
    '\n}\n'
  ).replace(/\r\n/g, '\n');
}

const STATIC_BLOCK_START = '/* design-tokens:start */';
const STATIC_BLOCK_END = '/* design-tokens:end */';

/** Replaces the marker-delimited token block, keeping the start marker's indentation. */
export function replaceStaticTokenBlock(consumerSource: string, css: string): string {
  const source = consumerSource.replace(/\r\n/g, '\n');
  const start = source.indexOf(STATIC_BLOCK_START);
  const end = source.indexOf(STATIC_BLOCK_END);
  if (start < 0 || end < start || source.indexOf(STATIC_BLOCK_START, start + 1) >= 0) {
    throw new Error('Expected exactly one ordered design-tokens marker pair');
  }
  const lineStart = source.lastIndexOf('\n', start) + 1;
  const indent = source.slice(lineStart, start);
  if (!/^[ \t]*$/.test(indent)) throw new Error('design-tokens:start must begin its line');
  const body = css
    .trimEnd()
    .split('\n')
    .map((line) => (line.length === 0 ? line : indent + line))
    .join('\n');
  return source.slice(0, start) + STATIC_BLOCK_START + '\n' + body + '\n' + indent + source.slice(end);
}

export const staticTokenConsumers = ['extension/popup.css', 'app/provisioning/provisioning.html'];
const repositoryRoot = path.resolve(themeDirectory, '..', '..', '..');

function writeIfChanged(filePath: string, content: string): boolean {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

export function generateColorReport(tokensJsonSource: string): string {
  return JSON.stringify(qualifyThemeColors(resolveTokens(tokensJsonSource)), null, 2) + '\n';
}

function main(): void {
  validateRepositoryConsumers(repositoryRoot);
  const tokensSource = fs.readFileSync(sourcePath, 'utf8');
  fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeIfChanged(generatedPath, generateThemeSource(tokensSource));
  const css = generateStaticTokensCss(tokensSource);
  writeIfChanged(staticTokensPath, css);
  console.log('Theme generated deterministically from tokens.json');
  const reportIndex = process.argv.indexOf('--color-report');
  if (reportIndex >= 0) {
    const output = process.argv[reportIndex + 1];
    if (!output || output.startsWith('--')) throw new Error('--color-report requires an output path');
    fs.mkdirSync(path.dirname(path.resolve(output)), { recursive: true });
    writeIfChanged(output, generateColorReport(tokensSource));
  }
  if (process.argv.includes('--static-surfaces')) {
    for (const consumer of staticTokenConsumers) {
      const consumerPath = path.join(repositoryRoot, consumer);
      const updated = replaceStaticTokenBlock(fs.readFileSync(consumerPath, 'utf8'), css);
      if (writeIfChanged(consumerPath, updated)) console.log('Updated design tokens in ' + consumer);
    }
  }
}

const isMainModule = process.argv[1] !== undefined
  && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMainModule) main();
