"""Canonical derivation and build-time embedding of the pinned extension ID."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
from typing import Sequence


def extension_identity_from_key(key: str) -> str:
    """Return the Chrome extension ID assigned to a manifest public key."""

    digest = hashlib.sha256(base64.b64decode(key, validate=True)).hexdigest()
    return "".join(chr(ord("a") + int(nibble, 16)) for nibble in digest[:32])


def extension_identity_from_manifest(manifest_file: Path) -> str:
    """Return the extension ID derived from one manifest's pinned key."""

    manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
    key = manifest["key"]
    if not isinstance(key, str):
        raise ValueError("extension manifest key must be a string")
    return extension_identity_from_key(key)


def write_embedded_extension_identity(manifest_file: Path, output_file: Path) -> None:
    """Write the frozen-only module from the current manifest key."""

    identity = extension_identity_from_manifest(manifest_file)
    output_file.write_text(
        '"""Generated by the Windows packaging build; do not edit."""\n\n'
        f'EXTENSION_ID = "{identity}"\n',
        encoding="utf-8",
    )


def embedded_extension_identity_matches(
    manifest_file: Path, embedded_file: Path
) -> bool:
    """Return whether a generated module contains the current manifest identity."""

    namespace: dict[str, object] = {}
    exec(embedded_file.read_text(encoding="utf-8"), namespace)
    return namespace.get("EXTENSION_ID") == extension_identity_from_manifest(manifest_file)


def main(argv: Sequence[str] | None = None) -> int:
    """Generate or verify the frozen extension-ID module for the build script."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--verify-embedded", type=Path)
    arguments = parser.parse_args(argv)
    if (arguments.output is None) == (arguments.verify_embedded is None):
        parser.error("supply exactly one of --output or --verify-embedded")
    if arguments.output is not None:
        write_embedded_extension_identity(arguments.manifest, arguments.output)
        return 0
    return int(
        not embedded_extension_identity_matches(
            arguments.manifest, arguments.verify_embedded
        )
    )


if __name__ == "__main__":
    raise SystemExit(main())
